### ISSUE TITLE
Can current master be build?

### ISSUE THREAD

**Issue by ThaDafinser** [gkralik/php7-sapnwrfc#1]
I got those 3 errors on windows.

Can u build it on unix?

![image](https://cloud.githubusercontent.com/assets/533017/12917252/a38c941a-cf38-11e5-909e-379997d5fff1.png)

**Comment by gkralik** [comment]
At the moment, current master does not build, I'm doing some refactor work.
The latest version that should build is 28dcb7336f3cb9178720cdfbada43e94a8d96df1.

**Comment by gkralik** [comment]
I'm currently implementing the `invoke()` method. It should be finished by the end of the week.
Also, I haven't tested on Windows (mostly because I don't have a Windows box), so I appreciate any help with that.

**Comment by ThaDafinser** [comment]
There i only have one missing external symbol

![image](https://cloud.githubusercontent.com/assets/533017/12917563/555cc812-cf3a-11e5-9711-07cf448ce38c.png)

What versions do you use to build on unix?
- php 7.0.3 (x86 or x64)
- sapnwrfc version?

**Comment by gkralik** [comment]
Ok, just noticed a missing method in that version. In `sapnwrfc.c#L594`, add the following:

```c
PHP_METHOD(FunctionEntry, invoke)
{}
```

Then it should compile.

**Comment by gkralik** [comment]
I'm using PHP 7.0.3 NTS and SDK version 7200.0.28.
I haven't given any attention to thread-safety, that might be an issue when using it on windows. I plan to do that as soon as the basics are working.

**Comment by ThaDafinser** [comment]
Works with that fix :+1: 

Then i try to build a valid `config.w32`

![image](https://cloud.githubusercontent.com/assets/533017/12917884/31d0b6b8-cf3c-11e5-8e5b-abd0686a7c7b.png)

**Comment by gkralik** [comment]
:+1:
I'll tell you as soon as `invoke()` is ready.

**Comment by ThaDafinser** [comment]
Cool. Just ping me and try to keep the `config.w32` from the PR updated.

**Comment by ThaDafinser** [comment]
Could build latest master.

With this part
```
PHP_METHOD(Connection, openConnection)
{
}
```

Just one warning is shown

![image](https://cloud.githubusercontent.com/assets/533017/13003580/a550a206-d176-11e5-9586-f543bab84c8b.png)

**Comment by gkralik** [comment]
Perfect. I'll have a look at the warning this weekend. I hope to have a usable version by Sunday :)

**Comment by ThaDafinser** [comment]
Wow, that would be awesome :+1: 

BTW, i asked at SAP support if it's allowed to get the NW RFC library public, to get automatic builds.
They told me i should ask here, but didnt got any reply until yet http://scn.sap.com/thread/3862034
I have not much hope to get a positive answer....

What do you think about publishing on pecl.php.net after the implementation is finished?
This would also allow to install it with pickle: https://github.com/FriendsOfPHP/pickle#introduction

**Comment by gkralik** [comment]
I would not object against putting it on PECL and making it installable via `pickle`. But let's wait what the SAP folks say. I'm not overly confident that they would allow it to be published. Also I'd probably want a written statement from them just to be on the safe side...

**Comment by ThaDafinser** [comment]
Yeah i also dont think they allow it. But still it could be provided on `pecl`. For pickle you need a build enviroment anyway, to build a extension on windows.

**Comment by gkralik** [comment]
Actually, if you put the SDK in some predefined path before using pickle to install it, it could work. In `config.m4` I'm checking a few default paths in case the user does not pass one with the `--with-sapnwrfc=` arg.

**Comment by gkralik** [comment]
I fixed the signed/unsigned mismatch. Can you try to build the current master on Windows? Should be a working prototype by now.

Also let's split out the PECL thing to a separate issue as soon as there is a reply from the SAP guys.

**Comment by ThaDafinser** [comment]
Just build it, it works partly. Great job :+1: 
DId not see any errors.

![image](https://cloud.githubusercontent.com/assets/533017/13028375/9ccb2de8-d26d-11e5-906c-b9e53613160d.png)

If i try it with `MSHOST` instead of `ASHOST` then the extension has an unknown error currently.

![image](https://cloud.githubusercontent.com/assets/533017/13028389/f988c022-d26d-11e5-87b1-23fca7130747.png)

**Comment by gkralik** [comment]
Strange. Can you provide more details? Some error message, a core dump, stack trace or anything?

**Comment by gkralik** [comment]
Also, when does the error occur? During connection or function lookup? Please provide the test script.
Also try to enable trace mode (option `'trace' => 2`) and attach the tracefile...

**Comment by ThaDafinser** [comment]
@gkralik i will try it on monday with trace enabled

**Comment by gkralik** [comment]
Thanks. Curious about what that is. Sadly, we don't have a system with load balancing any more, so it's quite difficult to test for me atm.

**Comment by ThaDafinser** [comment]
@gkralik that was easier then i thought :smile: 

The problem is, when you provide a boolean parameter, instead of the '0' like in your example
```
$config = [
    'ashost' => 'my.sap.system.local',
    'sysnr' => '00',
    'client' => '123',
    'user' => 'DEMO',
    'passwd' => 'XXXX',
    'trace' => true
];
```

**Comment by gkralik** [comment]
Ahh, ok, the parameters are just passed to the RFC lib directly... maybe we could convert boolean config vars to 0/1...

Glad it works :-)

**Comment by gkralik** [comment]
I'm closing the issue. Feel free to reopen or create a new one if you spot a problem.

**Comment by ThaDafinser** [comment]
Yep, this issue got too long. Thank you
