### ISSUE TITLE
Does this connector support PHP8?

### ISSUE THREAD

**Issue by szabizs** [gkralik/php7-sapnwrfc#102]
I was wandering if thie connector does support PHP8?

**Comment by gkralik** [comment]
Not yet - it's on the roadmap though, but I have no ETA at the moment.

**Comment by gkralik** [comment]
I have started working on PHP 8 support - not quite ready yet, though.

**Comment by gkralik** [comment]
Preliminary support for PHP 8.0 is on `main`. Report any issues you face.

**Comment by szabizs** [comment]
That is great news :) will test it put and provide feedback

**Comment by fscholzspryker** [comment]
Nice work @gkralik !!! 

Could you maybe also add a tag for the latest changes please?

**Comment by gkralik** [comment]
I have tagged a [2.0.0-beta1](https://github.com/gkralik/php7-sapnwrfc/releases/tag/2.0.0-beta1) release.

**Comment by gkralik** [comment]
Support for PHP 8.0 and PHP 8.1 has been added, starting with release *2.0.0-beta1*.
