### ISSUE TITLE
Building issues

### ISSUE THREAD

**Issue by SimoneSilini** [gkralik/php7-sapnwrfc#103]
Hello, 

I've been experiencing the string memory corruption bug from special characters and I see there is a fix already implemented in the current version of the source.
That said I'm experiencing an issue building the dll.
After following all the steps i invoke 'nmake' and it crashes with this error report:

`sapnwrfc.c
string_helper.c
c:\php-sdk\phpdev\vc15\x64\php-src\ext\sapnwrfc\php_sapnwrfc.h(16): fatal error C1083: Cannot open include file: 'version.h': No such file or directory (compiling source file ext\sapnwrfc\sapnwrfc.c)
ext\sapnwrfc\rfc_parameters.c(1484): warning C4018: '<': signed/unsigned mismatch
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe"' : return code '0x2'
Stop.`

**Comment by gkralik** [comment]
Building on windows is currently broken. I have it on my agenda for the coming days.

**Comment by gkralik** [comment]
This should now work again.

**Comment by SimoneSilini** [comment]
Hi,

I can confirm that this is working again and also fixed the string corruption / fast-cgi crash problem.

Thanks a lot
Simone
