### ISSUE TITLE
Not able to open connection to SAP server

### ISSUE THREAD

**Issue by rahulaepl** [gkralik/php7-sapnwrfc#106]
I am trying to connect to SAP from a Windows 2019 Standard Server 64-bit.

Getting this error 

Exception : Could not open connection

The library seems to be loading fine, but it is not able to connect to SAP. No trace file is getting generated even with the VERBOSE flag. 
Could you please help resolve this or help me switch on the trace file so that the problem is clearer?

My environment details are below:
PHP version is xampp-windows-x64-7.4.3-0-VC15
sapnwrfc dll used is php_sapnwrfc-1.3.0-7.4.3-vc15-ts-x64.dll. Downloaded built dll from github directly. Placed in php ext folder.
sapnwrfc is loaded & seen in phpinfo.
Have placed SAP SDK in c:\nwrfcsdk. Added c:\nwrfcsdk\lib to system path.
SAP NW RFC version is 7.5
User name and password is correct and verified. SAP server is pinging from my server.

Here is my code:

````php
<?php

use SAPNWRFC\Connection as SapConnection;
use SAPNWRFC\Exception as SapException;

$config = [
    'ashost' => '192.168.52.65:8000',
    'sysnr'  => '00',
    'client' => '340',
    'user'   => '####',
    'passwd' => '#####',
    'trace'  => SapConnection::TRACE_LEVEL_VERBOSE,
];

try {
    $c = new SapConnection($config);
	
    $f = $c->getFunction('Z_RFC_RTPD_GET_DATA');
    $result = $f->invoke([
        'I_DYELOT_SCHEDULE_DATE' => '2021-02-28'
    ]);

    var_dump($result);

} catch(SapException $ex) {
    echo 'Exception : ' . $ex->getMessage() . PHP_EOL;
}
````

**Comment by clcarver** [comment]
I would guess it has something to do with your configuration. 192.168. ip address implies your SAP install is installed locally? I am not sure how your connection is set up, but you can look here: https://help.sap.com/viewer/753088fc00704d0a80e7fbd6803c8adb/7.5.9/en-US/48a8e5f451343079e10000000a42189b.html

If you are using a router for a firewall, your connection settings will be different.

Also, the sapnwrfc.ini file located in your demo directory of the nwrfcsdk has many examples of various connection setups.

Lastly, you can turn on the full trace setting to see if that will help point you in the right direction.

**Comment by gkralik** [comment]
As far as I know, `ashost` does not take a port. The port is derived from `sysnr`. Look at the link provided by @clcarver .
