### ISSUE TITLE
can work in Laravel Controller, but not command

### ISSUE THREAD

**Issue by TingSyuanWang** [gkralik/php7-sapnwrfc#111]
Dear author @gkralik,

I met pretty strange thing, it's might be the Laravel issue, but I'd like to ask you here first.

Here is my controller code, it can show the result perfectly.
```
<?php

namespace App\Http\Controllers;
use SAPNWRFC\Connection as SapConnection;
use SAPNWRFC\Exception as SapException;

public function index()
{
    return SapConnection::version();
}
```

However, when I moved the code to command, it showed `Class 'SAPNWRFC\Connection' not found`
```
<?php

namespace App\Console\Commands;
use SAPNWRFC\Connection as SapConnection;
use SAPNWRFC\Exception as SapException;

class uploadSapStore extends Command
{
    protected $signature = 'sap:upload-sap-store';

    public function __construct()
    {
        parent::__construct();
    }

    public function handle()
    {
        Log::info(SapConnection::version());
    }
}
```

I'm using Laravel 8 and php7.4 in Homestead. Moveover, I created a Ubuntu 20.04 with nginx and php7.4 server, the result is identical.

Can I use absolute path when I import the package? (I didn't find absolute path, please tell me how to find the path.)
Or can you give me some hint?  Thanks in advance.

**Comment by clcarver** [comment]
Sometimes the cli runs a different php then the web server. I would dd php
info or maybe php -m from the console to see if the sapnwrfc module is
installed.

**Comment by TingSyuanWang** [comment]
Dear @clcarver,

Thanks for your kind help. It's helpful and solved my problem correctly.

I used `php --ini` to check my path, the real path is ` /etc/php/7.4/cli/php.ini`.
As the result, I changed the php.ini file from the above path.
After I changed the correct file, it worked as what I wanted.
