### ISSUE TITLE
Segmentation Fault error when I add sqlsrv driver

### ISSUE THREAD

**Issue by aacraf** [gkralik/php7-sapnwrfc#112]
I am trying to implement an RFC call to fetch some data and then, query to a SQL Server to do some filtering.

I can do the RFC Call and fetch the data without any problem when the pdo_sqlsrv.ini and sqlsrv.ini files are not in /etc/php/8.0/mods-available directory. 

When I add those two to the directory I get  this error:

```
PHP Warning:  Module "pdo_sqlsrv" is already loaded in Unknown on line 0

Violación de segmento
````

The sqlsrv drivers work and I can get data from the databases but it seems like there is a incompatibiliy between the sapnwrfc and pdo_sqlsrv or sqlsrv drivers. I am guessing It could be something about data types...

The sql drivers installed are the 5.9.0 version. PHP client version is the 8.0.8.

**Comment by aacraf** [comment]
I re-installed the latest version in the main repository and now i get this error instead of the Segmentation Fault...

```
PHP Warning:  Module "pdo_sqlsrv" is already loaded in Unknown on line 0

Array
(
    [code] => 22
    [key] => RFC_CONVERSION_FAILURE
    [message] => Illegal input during conversion from RFCTYPE_FLOAT to RFCTYPE_BCD
)
```

If I remove the sqlsrv files from the /etc/php/8.0/mods-available directory I can still fetch the data without any problem....

I add them again and I get this error.

**Comment by gkralik** [comment]
Please provide a backtrace when you encounter a Segmentation fault.

**Comment by aacraf** [comment]
The error happens when I call the function invoke to get the custom function module (If I call the STRF_CHANGING module it works).

I am sorry If that's not the answer but I don't really know what you mean by "backtrace". Do u want me to show a specific log or try a specific code?

**Comment by gkralik** [comment]
> `PHP Warning:  Module "pdo_sqlsrv" is already loaded in Unknown on line 0`

This means you are trying to load the module twice. Check your PHP configuration files.

As for the conversion error, I will need additional information. Please provide the exact version of the `sapnwrfc` extension (git revision if not a release) and a complete, self-contained example for me to try and reproduce (PHP code and a small ABAP function module if necessary).

If you encounter a Segmentation fault, you will have to use a debug build of PHP and the extension and then extract a backtrace from the coredump using gdb. Google is your friend on how to do that.

Note that PHP 8 support is still experimental at the moment.

**Comment by aacraf** [comment]
I am using the last version of the sapnwrfc extension with the php 8.0 support. 

The php code i'm trying to run:

```php
	use SAPNWRFC\Connection as SapConnection;
	use SAPNWRFC\Exception as SapException;
	
	// Función que devuelve todos los pedidos realizados de una planta en un rango de fecha [dtFechaInicio - dtFechaInicio] (fmt: YYYYMMDD) 
	function rfcPedidos($strPlanta, $dtFechaInicio, $dtFechaFin)
	{			
		// definimos los parametros de conexion 
		// TODO: Los parametros vienen de la BDD.
		$config = [
			'ashost' => 'XXXX',
			'sysnr'  => 'XX',
			'client' => 'xxx',
			'user' => 'xxxx',
			'passwd' => 'xxxxx',
			'lang' => 'ES',
			'trace'  => SapConnection::TRACE_LEVEL_OFF,
		];
		
		$parameters = [
			"P_WERKS" => $strPlanta,
			"P_BUDAT_LOW" => $dtFechaInicio,
			"P_BUDAT_HIGH" => $dtFechaFin
		];


		//$f = $c->getFunction('ZPE_MM_EXT_POS_PEDIDOS_MECAL');
	
		try {
			
			// creamos la conexion RFC

			$c = new SapConnection($config);
			$f = $c->getFunction('ZPE_MM_EXT_ALBAR_MECAL');

		
			$result = $f->invoke($parameters);
                        // fails here...



			//var_dump($result);

			// array que contendra todos los repartos correspondientes a sus posiciones y cabeceras.
			$pedidos = [];
			
			// Mostrar datos de las diferentes tablas que devuelve el SA
			foreach($result["I_HISTORIAL"] as $pedido){
				
				$a = array(
					"Numero de pedido" => $pedido["EBELN"],
					"Pos pedido: " => $pedido["EBELP"],
					"Año: " => $pedido["GJAHR"],
					"Documento SAP: " => $pedido["BELNR"],
					"Fecha contabilización: " => $pedido["BUDAT"],
					"Cantidad: " => $pedido["MENGE"],
					"Coste: " => $pedido["DMBTR"],
					"Albarán: " => $pedido["XBLNR"], 
					"Material: " =>  $pedido["MATNR"],  
					"Usuario SAP: " => $pedido["ERNAM"]
				);
				
				array_push($pedidos, $a);
			
				
			}


			print_r($pedidos);
	
			$c->close();
		 } catch(SapException $ex) {
			print_r($ex->getErrorInfo()) . PHP_EOL;
		}
```

I am no getting a segmentation fault core dump anymore so I don't know how to get the backtrace for that run. I tried this:

```
(gdb) run server.php
Starting program: /usr/bin/php server.php
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Array
(
    [code] => 22
    [key] => RFC_CONVERSION_FAILURE
    [message] => Illegal input during conversion from RFCTYPE_FLOAT to RFCTYPE_BCD
)
[Inferior 1 (process 11648) exited normally]
(gdb) bt
No stack.
(gdb)
```

I am also attaching the result of executing phpinfo() command in case it helps.

[test.txt](https://github.com/gkralik/php7-sapnwrfc/files/6838926/test.txt)

**Comment by gkralik** [comment]
How does `ZPE_MM_EXT_ALBAR_MECAL` look like? What data types are returned? Have you tried setting `lang` to `EN`?

**Comment by aacraf** [comment]
The datatype conversion is the fallowing
![image](https://user-images.githubusercontent.com/30293728/126505848-1827a8b8-d9df-4113-b31f-13c1984744e1.png)

It seems that there is an issue with the fallowing datatype... 

![image](https://user-images.githubusercontent.com/30293728/126505346-63bcf4ef-2d0f-4e20-9b1e-da765d42b27e.png)

I tried to change lang to EN and still getting the same error.

What i don't really understand is that when i remove the sqlsrv drivers the conversion works and and I get correctly all the values. The sqldriver affects  somehow the conversion behaviour.

**Comment by gkralik** [comment]
OK, thanks for the information, I'll try to have a look tomorrow evening...

**Comment by gkralik** [comment]
I am unable to reproduce this issue...
