### ISSUE TITLE
Failed to get FLOAT parameter "SAP_FIELD_NAME"

### ISSUE THREAD

**Issue by gustumahendra** [gkralik/php7-sapnwrfc#113]
Hello, does anyone encounter this error when using RFC library on linux ? 
I am currently unable to get any type of FLOAT or DECIMAL field from SAP, the error said :
Failed to get FLOAT parameter "SAP_FIELD_NAME"

but if I use the same library with the same version of PHP (7.4) on windows, it's working well
how to fix this ? can anyone help ?
![error RFC](https://user-images.githubusercontent.com/88175623/127596626-d0535453-7cd3-4b5f-ab29-18995a1a1de4.png)

**Comment by gkralik** [comment]
Which versions (PHP, SAP NW RFC SDK, extension) are your using?

Please share share a minimal, reproducible example (PHP + ABAP code).

**Comment by gkralik** [comment]
I have just tested this with the latest version from `main` using PHP 7.4.16 and PHP 8.0.2 on Linux. I have no problems retrieving FLOAT, DECF16 and DECF34 parameter values.
