### ISSUE TITLE
Could not open connection

### ISSUE THREAD

**Issue by hercross** [gkralik/php7-sapnwrfc#115]
Hi, I'm trying to use sapnwrfc with php 7.4.21.

I've used saprfc with php5, and now I've upgrade my php and I want to use sapnwrfc.

I load the library, and in my php_info I can see the library is loaded, version 1.4.0 for SAP NW RFC SDK 7500.0.8

Ok, now I've tried to maka a connection:

`<?php
use SAPNWRFC\Connection as SapConnection;
use SAPNWRFC\Exception as SapException;

 

/*
use sapnwrfc;
use sapnwrfcConnectionException;
use sapnwrfcCallException;
*/

 

$config = [
    'ashost' => 'local.ip.sap',
    'sysnr'  => '00',
    'client' => '011',
    'user' =>   'user',
    'passwd' => 'Password',
];

    try{
        $conn = new SapConnection($config);
        $f = $conn->getFunction('ZMMDI_WS_VEDNOR_LIST');
        $result = $f->invoke();
        print_t($result);
    }catch(Exception $e){
        echo $e->getMessage(). PHP_EOL;
    }
?>`

But I get an exception "Could not open connection".

What am I doing wrong??
Can I test anything?

Thanks!!

**Comment by gkralik** [comment]
Are your connection details correct? Use the `trace` setting to get an idea what is wrong.

**Comment by hercross** [comment]
Hi gkralik, thanks for ansred to me..

Yes, the connection details are correct, are the same that I was using before with saprfc library.
How can I use trace??

Now, in my config I added: 'trace'  => SapConnection::TRACE_LEVEL_FULL, but where can I see it?

Thanks

**Comment by gkralik** [comment]
There should be `*.trc` files in the working directory.

**Comment by hercross** [comment]
No, nothing.

I'm using Xamp to test it. And the working directory is c:\XAMPP\htdocs\

There I have test.php, is my file, but ho have *.trc.

Nedd activate any more?

Thanks

**Comment by gkralik** [comment]
I don't know about XAMPP.
If you set the `trace` option, the extension instructs the SAP NW RFC SDK to generate a trace file. Maybe no trace file is generated for some reasons.

Look at the exception's `errorInfo` property, it might contain additional information.

**Comment by hercross** [comment]
I get this...

SAPNWRFC\ConnectionException: Could not open connection in C:\xampp\htdocs\test.php:34 Stack trace: #0 C:\xampp\htdocs\test.php(34): SAPNWRFC\Connection->__construct(Array) #1 {main}

**Comment by gkralik** [comment]
Again: ConnectionException should have an `errorInfo` property.

**Comment by hercross** [comment]
Hi, I have a *.trc file, are in other directory..


**** Trace file opened at 2021-08-24 12:26:12.781455 UTC+02:00 (Hora estándar romance), Encoding UTF-8
NW RFC Library: SDK variant, Release 750 Patch Level 8, Compiled on Apr 17 2021 03:23:42
 CPIC library: 753.2020.03.230 version 3, NI library: 40, Kernel Release: 753 Patch Level 814
 Current working directory: C:\xampp, Program: httpd
 Hardware: PC with Windows NT 8x AMD64 Level 6 (Mod 58 Step 9), Operating_system: Windows NT 10.0
 Hostname: BNAZR1307, IP address: 10.15.38.108, IPv6 address: fe80::4c76:212e:c890:d89a

>> Passed parameters
	ASHOST: 10.196.1.70
	CLIENT: 011
	PASSWD: (- secret -)
	SYSNR: 00
	TRACE: 3
	USER: DP16BNA
<< Passed parameters

2021-08-24 12:26:12.782607 [16232] >> RfcOpenConnection
>> RfcOptions
	Partner Char Size: 1
	Client: 011
	User: DP16BNA
	Alias: 
	Passwd: (- secret -)
	Language: 
	SysNr: 00
	ASHost: 10.196.1.70
	ASService: 
	GWHost: 
	GWService: 
	R3Name: 
	MSHost: 
	MSService: 
	TLS Cryptolib: 
	TLS Trust All: Off
	Codepage: 1100
	Trace: 3
	LogonCheck: 1
	CompressionType: 1
	Serialization: 0
	Ignore Char Conv Errors: 0
	Substitution Char: 35
	UseRoundtripOptimization: 0
	SO Keepalive: 0
	CPIC Keepalive: 0
	Delta Manager: 1
<< RfcOptions

2021-08-24 12:26:12.782791 [16232] 	>> RfcOptions::determineType
determined type RFC_CLIENT
2021-08-24 12:26:12.782880 [16232] 	<< RfcOptions::determineType returned 0

2021-08-24 12:26:12.782932 [16232] 	>> RfcConnection::openNew
2021-08-24 12:26:12.783054 [16232] 	>> RfcConnection::connect
2021-08-24 12:26:12.783118 [16232] 	>> CpicConnection::connectAsClient
2021-08-24 12:26:13.061092 [16232] 	<< CpicConnection::connectAsClient returned 0

2021-08-24 12:26:13.061206 [16232] 	>> RfcConnection::setConnOptions
2021-08-24 12:26:13.074933 [16232] 	<< RfcConnection::setConnOptions returned 0

2021-08-24 12:26:13.075031 [16232] 	>> RfcConnection::writeRfcSessionLogon
2021-08-24 12:26:13.075082 [16232] 	<< RfcConnection::writeRfcSessionLogon returned 0

>> HEXDUMP
2021-08-24 12:26:13.075172 [16232] Sending data for handle 2274276451568, convID 30620954, codepage 1100
000000 | D9C6C3F0 F0F0F0F0 F0F0F0E3 01010008 |ÙÆÃððððððððã....|
000010 | 03010101 01010000 01010103 00040000 |................|
000020 | 0E0B0103 0106000B 04010003 000A0200 |................|
000030 | 00002301 06011400 03303131 01140111 |..#......011....|
000040 | 00074450 3136424E 41011101 17000D29 |..DP16BNA......)|
000050 | 400A0065 5BAF0F85 6F245A4A 01170115 |@..e[¯..o$ZJ....|
000060 | 00000115 05010001 01050100 07000C31 |...............1|
000070 | 302E3135 2E33382E 31303800 07001800 |0.15.38.108.....|
000080 | 19666538 303A3A34 6337363A 32313265 |.fe80::4c76:212e|
000090 | 3A633839 303A6438 39610018 00110001 |:c890:d89a......|
0000a0 | 45001100 12000337 35330012 00130003 |E......753......|
0000b0 | 37353300 13000800 09424E41 5A523133 |753......BNAZR13|
0000c0 | 30370008 00060009 3C756E6B 6E6F776E |07......<unknown|
0000d0 | 3E000601 30000568 74747064 01300502 |>...0..httpd.0..|
0000e0 | 00000502 000B0003 37353300 0B010200 |........753.....|
0000f0 | 07524643 50494E47 0102FFFF 0000FFFF |.RFCPING..ÿÿ..ÿÿ|
<< HEXDUMP

2021-08-24 12:26:13.075430 [16232] 	>> RfcConnection::readUpTo
>> HEXDUMP
2021-08-24 12:26:13.155784 [16232] Receiving data for handle 2274276451568, convID 30620954, codepage unknown
000000 | 01010008 01010101 01010000 01010103 |................|
000010 | 00040000 0E0B0103 0106000B 04010003 |................|
000020 | 00030200 00002301 06001600 04313130 |......#......110|
000030 | 30001600 07000F31 302E3139 362E312E |0......10.196.1.|
000040 | 37302020 20200007 0018000B 31302E31 |70    ......10.1|
000050 | 39362E31 2E373000 18000800 126C6362 |96.1.70......lcb|
000060 | 69706563 63646231 5F503530 5F303000 |ipeccdb1_P50_00.|
000070 | 08001100 01330011 00130004 37323220 |.....3......722 |
000080 | 00130012 00043730 30200012 00060009 |......700 ......|
000090 | 3C756E6B 6E6F776E 3E000601 30000853 |<unknown>...0..S|
0000a0 | 41504D53 53593101 30050000 00050004 |APMSSY1.0.......|
0000b0 | 02004043 6F6E6E65 78696F6E 20706172 |..@Connexion par|
0000c0 | 206D6F74 20646520 70617373 65206E27 | mot de passe n'|
0000d0 | 65737420 706C7573 20706F73 7369626C |est plus possibl|
0000e0 | 65203A20 74726F70 206427E9 63686563 |e : trop d'échec|
0000f0 | 73202104 02FFFF00 00FFFF00 00000000 |s !..ÿÿ..ÿÿ.....|
<< HEXDUMP

2021-08-24 12:26:13.156640 [16232] 	>> RfcConnection::readUpTo
Received RFCID 0x0101 (257), 8 bytes
Received RFCID 0x0103 (259), 4 bytes
Received RFCID 0x0106 (262), 11 bytes
Received RFCID 0x0016 (22), 4 bytes
Skipping RFCID 0x0016 (22), 4 bytes
Received RFCID 0x0007 (7), 15 bytes
Received RFCID 0x0018 (24), 11 bytes
Received RFCID 0x0008 (8), 18 bytes
Received RFCID 0x0011 (17), 1 byte
Received RFCID 0x0013 (19), 4 bytes
Received RFCID 0x0012 (18), 4 bytes
Received RFCID 0x0006 (6), 9 bytes
Received RFCID 0x0130 (304), 8 bytes
Received RFCID 0x0500 (1280), 0 bytes
Skipping RFCID 0x0500 (1280), 0 bytes
Received RFCID 0x0402 (1026), 64 bytes
Received RFCID 0xFFFF (65535), 0 bytes
Skipping RFCID 0xFFFF (65535), 0 bytes
2021-08-24 12:26:13.158643 [16232] 	<< RfcConnection::readUpTo returned 0

2021-08-24 12:26:13.158928 [16232] 	<< RfcConnection::readUpTo returned 4

2021-08-24 12:26:13.159160 [16232] 	<< RfcConnection::connect returned 4

2021-08-24 12:26:13.162565 [16232] >> Exception occurred
	[Handle: 2274276451568	ConvID: 30620954	Target: lcbipeccdb1	SysID: P50	SysNr: 00	User: DP16BNA	Mandant: 011	Language: 	Codepage: 4103]
	RfcABAPMessageException: Key: , Code: RFC_ABAP_MESSAGE, Message: Connexion par mot de passe n'est plus possible : trop d'échecs !
2021-08-24 12:26:13.162754 [16232] 	<< RfcConnection::openNew returned 2

2021-08-24 12:26:13.162894 [16232] 	>> RfcConnection::disconnect
2021-08-24 12:26:13.163012 [16232] 	>> CpicConnection::close
2021-08-24 12:26:13.163128 [16232] 	<< CpicConnection::close returned 0

2021-08-24 12:26:13.163247 [16232] 	<< RfcConnection::disconnect returned 0

2021-08-24 12:26:13.163437 [16232] << RfcOpenConnection returned RFC_LOGON_FAILURE
	RFC_ERROR_INFO.key: RFC_LOGON_FAILURE
	RFC_ERROR_INFO.message: Connexion par mot de passe n'est plus possible : trop d'échecs !

**Comment by hercross** [comment]
too many failures! I'm goping to unlock the user and test again..
