### ISSUE TITLE
Memory leak investigation - v1.4.0 and earlier

### ISSUE THREAD

**Issue by clubcentives** [gkralik/php7-sapnwrfc#119]
Hi Gregor and team,

Thank you for your excellent work over the years on this connector. We've used it successfully for quite a while, but have become plagued by what appears to be a "memory leak"; what we're seeing is that memory usage grows over time until Windows crashes. 

I've assembled a php-only test script to demonstrate what we're experiencing that you can also run -- this is with php 7.4.22, SAP NW libraries 7.50, and a freshly compiled 1.4.0 version of the connector:

[https://www.evernote.com/shard/s3/sh/2715e325-0254-2d3d-17ce-532c759522b2/d01607d5ebdb248df68e2fa296ae5172](https://www.evernote.com/shard/s3/sh/2715e325-0254-2d3d-17ce-532c759522b2/d01607d5ebdb248df68e2fa296ae5172)

I'm not a C#/++ developer, so am wondering if you more-competent-than-I can have any ideas of what's causing this, and what a fix or workaround might be?

**Comment by clubcentives** [comment]
Please see my additional findings at the bottom of the above evernote doc. The findings, in short are:
(1) connect(), disconnect(), and getFunction() are not to "blame": memory usage remains level when these are used
(2) invoke() alone triggers the memory leak behavior
(3) setting use_function_desc_cache to false, calling clearFunctionDescCache($bapiName), nor setting the trace level manually to 0 have no effect - memory usage still compounds in calls to invoke()

**Comment by gkralik** [comment]
Hi, thanks for the comprehensive write-up. I'll have a look at this after my holiday.

**Comment by gkralik** [comment]
Quick question: are you able to reproduce with the current version of the extension in `main`?

**Comment by gkralik** [comment]
Also, your `phpinfo()` screenshot indicates you are using SDK version 7.20 (`7210.0.35`)?

**Comment by clubcentives** [comment]
Excellent catch. Let me fix this and retry.

**Comment by clubcentives** [comment]
THANK YOU - I've confirmed that the memory leak was resolved by correctly installing the SAP NW 7.50 libraries in the system32 folder. The final two graphs in my doc below say it all : )
https://www.evernote.com/shard/s3/sh/f034f578-d47c-e5ab-534c-cb01caf060d8/
Best,
