### ISSUE TITLE
Exception: Failed to get description for field

### ISSUE THREAD

**Issue by uiliands** [gkralik/php7-sapnwrfc#120]
Hello,

I created a function module and a program in php to connect to it by function invoke.
Althought I could create and use the program without problems on our development environment, I get an error on test environment indicating "Exception: Failed to get description for field BUKRS".

I saw the extension source code and I could see the error is related to function RfcGetFieldDescByName. It seems to return RFC_OK as false when we try to use it.
We already checked our abap code on function module and our code in php in both environments and we could see that both are exactly the same.

I am using php7-sapnwrfc on PHP 7.2.9 for Windows, php_sapnwrfc-1.2.1-7.2.9-vc15-ts-x86.dll with SAP NW RFC SDK 7.50.

Is there any requirement from SAP side? Or anything specific from the extension?
I would appreciate any possible clues.

Kind regards,

Uilian Kumagai

**Comment by gkralik** [comment]
Try the latest version of the extension with a current, supported PHP version. There have been many small improvements and I do not have the time to support old PHP or extension versions.
