### ISSUE TITLE
2.0.0.Beta1 vs 2.0.0.Beta2 PHP 8.0.X versions 

### ISSUE THREAD

**Issue by fikusir** [gkralik/php7-sapnwrfc#124]
### Question

Hi, in the realease of 2.0.0. Beta1 I see compiled plugin in version 8.0.15. In Beta2 I see 8.0.13.

For me the version 8.0.15 doesnt exists, so it should be 8.0.12?

Thank you so much and thank you for this awesome plugin!

**Comment by gkralik** [comment]
I might have messed up the version, yeah... Shouldn't matter though.

**Comment by fikusir** [comment]
Just wanted to inform you :) In original question I asked you also if you will publish new Win binary, but I made my own build - thanks for you GOOD instructions! Closing. Have a perfect day sir
