### ISSUE TITLE
php module api version discrepancy 

### ISSUE THREAD

**Issue by Lindo-OTG** [gkralik/php7-sapnwrfc#125]
### Bug Report

| Q                         | A     |
| ------------------------- | ----- |
| PHP version               | 8 |
| SAP NW RFC SDK version  |7.5| 
| Extension version/git ref |php_sapnwrfc-2.0.0-beta2-7.4.26-vc15-nts-x64 |

#### Summary
php -m
PHP Startup: sapnwrfc: Unable to initialize module
Module compiled with module API=20200930
PHP    compiled with module API=20210902
These options need to match

**Comment by gkralik** [comment]
You cannot use a pre-built DDL for PHP 7.4 on PHP 8.
/close
