### ISSUE TITLE
Unable to load module.

### ISSUE THREAD

**Issue by stuli3** [gkralik/php7-sapnwrfc#128]
### Bug Report

| Q                         | A     |
| ------------------------- | ----- |
| PHP version               | 8.0.17 |
| SAP NW RFC SDK version    | 7.50.9 |
| Extension version/git ref | 2.0.0-beta2 |

#### Summary

PHP write this error when loading the module:
The procedure entry point RfcGetInt8 could not be located in the dynamic link library C:\Program Files\PHP\v8.0.17\ext\php_sapnwrfc.dll

I have tried your dll and I have tried a new build with php8.0.17, but both throw the same error.

**Comment by stuli3** [comment]
It worked on another computer. I think I don’t find an old build garbage on the original machine.... I'm sorry to bother you

**Comment by cnjackchen** [comment]
I encountered the same problem.
I've tried PHP version 8.1.0 and 8.1.4.
