### ISSUE TITLE
Convert connection parameter boolean

### ISSUE THREAD

**Issue by ThaDafinser** [gkralik/php7-sapnwrfc#13]
This one works
```php
$config = [
    // ...
    'LCHECK' => '0',
    'TRACE' => '0',
    
    // ...
];
```

but this one not (worked at piersharding/php-sapnwrfc)
```php
$config = [
    // ...
    'LCHECK' => false,
    'TRACE' => false,
    
    // ...
];
```

**Comment by gkralik** [comment]
I have a fix for that in the pipeline. I should find some time tuesday evening to fix it.

**Comment by ThaDafinser** [comment]
cool thing :+1:

**Comment by gkralik** [comment]
OK, what exaxtly happens when you pass a boolean? For me, everything seems good. What does not work however is passing an integer value for the trace level (causes a segfault).

**Comment by ThaDafinser** [comment]
Also a segfault. Maybe it's only for that parameter (always changed both)

**Comment by gkralik** [comment]
Quite interesting...

**Comment by ThaDafinser** [comment]
Just tried it with only `LCHECK`. Only `0` or `1` as a string was valid.

Providing at (int) or (bool) was always a segfault

**Comment by gkralik** [comment]
Ok, thanks.
