### ISSUE TITLE
Unable to load dynamic library 'sapnwrfc'

### ISSUE THREAD

**Issue by cnjackchen** [gkralik/php7-sapnwrfc#130]
### Bug Report

| PHP version                           | 8.1.4 |
| SAP NW RFC SDK version     | 7200.610.22 |
| Extension version/git ref       | 2.0beta2 |

#### How to reproduce
Double click php.exe
or
run php.exe from command line window

Error:
Unable to load dynamic library 'sapnwrfc'.
The procedure entry point RfcGetInt8 could not be located in the dynamic link library C:\php\ext\php_sapnwrfc.dll

**Comment by cnjackchen** [comment]
I've tried php 8.1.0 and 8.1.4, both failed to load the dll.
Could you please have a look and fix this bug?
Thanks a lot!

**Comment by clcarver** [comment]
I think support for <7.5 was dropped. If possible, download the 7.5 version of the SAP SDK and try that.

**Comment by gkralik** [comment]
Sorrry for the late reply.

Yes, as @clcarver mentioned the newest version does not support the 7.20 SDK. Use the 7.50 SDK and make sure the library files are in the path.
