### ISSUE TITLE
undefined symbol: _zval_ptr_dtor

### ISSUE THREAD

**Issue by ynnoig** [gkralik/php7-sapnwrfc#131]
### Bug Report

| Q                         | A     |
| ------------------------- | ----- |
| PHP version               | 7.4.30 |
| SAP NW RFC SDK version    | 7.50 |
| Extension version/git ref | Tag 1.4.0 |

#### Summary

On SLE 15SP3 we have compiled and installed the sapnwrfc extension and the extension is loaded without problems.
On runtime we get the following error in apache2/error_log:

`/usr/sbin/httpd-prefork: symbol lookup error: /usr/lib64/php7/extensions/sapnwrfc.so: undefined symbol: _zval_ptr_dtor`

PHP Version

```
PHP 7.4.30 (cli) (built: Jun 10 2022 12:00:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.30, Copyright (c), by Zend Technologies
```

PHP Modules

```
[PHP Modules]
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
intl
json
libxml
mbstring
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
phalcon
Phar
psr
readline
Reflection
sapnwrfc
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

#### Current behavior

No RFC Call possible

#### How to reproduce

Try to compile and install the library on SUSE SP3 with apache 2 and PHP Version 7.4.30.

#### Expected behavior

If the extension is compiled and installed correctly should works in runtime too.

**Comment by gkralik** [comment]
Try with the latest version in `main` (or *2.0.0-beta2*). The *1.x* versions really are for PHP 7.2 only and are not maintained anymore.

**Comment by ynnoig** [comment]
I have already tried without success! :(

... But... I have other systems running in docker apache-buster php7.4 with 1.4.0 Version and everything works without problems.

I think that maybe is more related to SUSE 15 SP3 and php version 7.4.30? 

I searched yesterday the whole afternoon and evening about this problem, but no success... nothing found.

**Comment by gkralik** [comment]
Might be, I haven't use SUSE in more than a decade. I'll have a look when time allows.

**Comment by ynnoig** [comment]
Hi @gkralik, did u get time to test with SUSE?
