### ISSUE TITLE
Version 2.0.0 stable release

### ISSUE THREAD

**Issue by philipphaeusle** [gkralik/php7-sapnwrfc#132]
Is there a plan for the version 2.0.x stable release (for PHP 8.1.2 support)?
Or are there any known issues in the beta2 that would prevent a production use?

Thanks,
Philipp

**Comment by gkralik** [comment]
Thanks for reminding me. I do have some small things on my list, but life got in the way :wink: 

I cannot think of anything that would prevent production use. I'll try to find a few free hours to look over everything soon.
