### ISSUE TITLE
Not Build 

### ISSUE THREAD

**Issue by dedisupriadi1612** [gkralik/php7-sapnwrfc#134]
hello can you help me. i build sdk sapnwrfc  in windows, i've followed the steps on how to build the extentions but i found a problem where the extension is not there , realase or realse_ts not found php_sapnwrfc.dll

and i check and I checked the configuration time
![image](https://user-images.githubusercontent.com/26077025/184070696-327973c7-7772-4d48-8a08-3b9f495934bf.png)

**Comment by gkralik** [comment]
Are you sure you followed all the steps in the build instructions? The sapnwrfc extension obviously is not enabled during configure.

**Comment by FredMK** [comment]
I can confirm that something is not right with the current Windows build instructions.
There is no problem with the [previous one](https://github.com/gkralik/php7-sapnwrfc/blob/07f6c6ef334660640ce5ee3e2f0c16afc0bb3ad1/docs/building.rst).
