### ISSUE TITLE
SAPNWRFC Library returns error no conversation found with id 04395046 on certain words

### ISSUE THREAD

**Issue by gustumahendra** [gkralik/php7-sapnwrfc#135]
Hi, i want to ask a problem that's emerging and caught my attention recently.
Let's say I have a RFC that returns material data when I do search for material name for at least 3 character, everything works just great except for this spesific word i've found to be a problem. When I search for words 'prost' it returns 
![image](https://user-images.githubusercontent.com/88175623/185567120-1aba5e29-93a5-4df9-8d0c-005c28992325.png)

and when I search for 'prost r', it returns what I expected to be returned, and nothing else affected so far or yet I've just found that word. So what exactly causing this issue ? do I need something to be configured on PHP side ? Thank you

**Comment by gkralik** [comment]
Looks like some sort of encoding issue. Check if your FM returns some special characters (foreign scripts, etc).
