### ISSUE TITLE
Exception: Failed to get description for parameter TMP

### ISSUE THREAD

**Issue by poyukao** [gkralik/php7-sapnwrfc#136]
### Question

Hi,  I can run your sample program for FM: STFC_CHANGING very well.
 I have copied FM: STFC_CHANGING into FM: ZZ_PHP_TEST02, then it worked well also.
But if I renamed parameter: START_VALUE to TMP, when I INVOKE FM: ZZ_PHP_TEST02, I got an error message: Exception: Failed to get description for parameter TMP

Did I do anything wrong?
Does this mean I cannot call my own add-on RFC?

Thanks for your kindly help in advance.

-->

**Comment by gkralik** [comment]
Hmm, make sure your custom FM is activated and marked as remote-enabled.

**Comment by poyukao** [comment]
I'm very sure it is activated and remote-enabled.
When parameter name is START_VALUE, after parameter name changed , Exception: Failed to get description for parameter TMP
QQ

**Comment by poyukao** [comment]
I found if I restart Apache service, then it works well.
It seems the buffer in Apache does NOT refresh after I changed FM in SAP.
Is there any function to refresh the buffer and synchronize SAP and Apache?

Thanks

**Comment by gkralik** [comment]
[Manually clearing the function module description cache](https://gkralik.github.io/php7-sapnwrfc/usage.html#manually-clearing-the-function-module-description-cache)
