### ISSUE TITLE
SAP NWRFC is not a valid win32 version

### ISSUE THREAD

**Issue by noaimwastaken** [gkralik/php7-sapnwrfc#145]
### Bug Report

| Q                         | A     |
| ------------------------- | ----- |
| PHP version               |8.1 |
| SAP NW RFC SDK version    |7.50 |
| Extension version/git ref | x.y.z |

#### Summary

When try to load php_sapnwrfc.dll i get (%1 is not a valid Win32 application) error.
I'm using it on 64 bit Windows 2016 Server Datacenter and still i get that error.

#### Expected behavior
That sapnwrfc will load

**Comment by gkralik** [comment]
What extension build did you try to use?
