### ISSUE TITLE
PHP Fatal error: Possible integer overflow in memory allocation (1610760192 32 + 32)

### ISSUE THREAD

**Issue by maciej123m** [gkralik/php7-sapnwrfc#150]
### Bug Report

| Q                         | A     |
| ------------------------- | ----- |
| PHP version               | 8.1 |
| SAP NW RFC SDK version    | 2.0 Beta 2 |
| Extension version/git ref | 2.0 Beta 2 |

#### Summary

At random times when connecting to SAP, the error "PHP Fatal error:
Possible integer overflow in memory allocation (1610760192 32 + 32)".

#### Current behavior

Random error with higher application load.

#### How to reproduce

Random application failure with more user load on the application. 
I am unable to reproduce this error intentionally.

**Comment by ynnoig** [comment]
I had the same problem and was related to latest version of nwrfcsdk... (i think level patch 11 was). Just downgrade it and then it works again. So was in my case!

**Comment by noaimwastaken** [comment]
> I had the same problem and was related to latest version of nwrfcsdk... (i think level patch 11 was). Just downgrade it and then it works again. So was in my case!
I'm using sdk 7.50 patch level 12, Could you tell me on which version you had that issue and to which one did you downgrade to?
