### ISSUE TITLE
PHP Startup: Unable to load dynamic library php_sapnwrfc.dll

### ISSUE THREAD

**Issue by BjorgeSO** [gkralik/php7-sapnwrfc#153]
### Question

I have been trying to install the sapnwrfc PHP extension for windows, and have tried using the pre-compiled extensions found here https://github.com/gkralik/php7-sapnwrfc/releases and also tried compiling PHP with the sapnwrfc extension aswell. Both results in "Warning: PHP Startup: Unable to load dynamic library 'php_sapnwrfc.dll'". I have tried several PHP versions and some of the pre-compiled sapnwrfc dll's. Note that I am trying using a Windows Docker Container, also did this using a Linux container which worked fine. While building myself I get some warnings:

C:\php-sdk\phpdev\vs16\x64\php-src
$ nmake
 
Microsoft (R) Program Maintenance Utility Version 14.29.30153.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Recreating build dirs
Recreating build dirs
        type ext\pcre\php_pcre.def > C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS\php8ts.dll.def
exceptions.c 
rfc_parameters.c 
C:\php-sdk\phpdev\vs16\x64\php-src\Zend\zend_gc.h(120): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data (compiling source file ..\modules\sapnwrfc\rfc_parameters.c) 
C:\php-sdk\phpdev\vs16\x64\php-src\Zend\zend_gc.h(120): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data (compiling source file ..\modules\sapnwrfc\exceptions.c) 
..\modules\sapnwrfc\rfc_parameters.c(1589): warning C4018: '<': signed/unsigned mismatch 
sapnwrfc.c 
string_helper.c 
C:\php-sdk\phpdev\vs16\x64\php-src\Zend\zend_gc.h(120): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data (compiling source file ..\modules\sapnwrfc\string_helper.c) 
C:\php-sdk\phpdev\vs16\x64\php-src\Zend\zend_gc.h(120): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data (compiling source file ..\modules\sapnwrfc\sapnwrfc.c)

The build still completes with this ouput:
Finished generating code
EXT sapnwrfc build complete
php_cli.c
php_cli_process_title.c
php_cli_server.c
php_http_parser.c
ps_title.c
   Creating library C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS\php.lib and object C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS\php.exp
SAPI sapi\cli build complete

You can see the release directory and the "php -c tmp-php.ini" command below:
 Directory of C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS

11/16/2023  02:33 PM    <DIR>          .
11/16/2023  02:33 PM    <DIR>          ..
11/16/2023  02:15 PM    <DIR>          devel
11/16/2023  02:11 PM           118,784 edit_a.pdb
11/16/2023  02:15 PM    <DIR>          ext
11/16/2023  02:29 PM                18 extension_dlls.txt
11/16/2023  02:32 PM    <DIR>          main
11/16/2023  02:15 PM    <DIR>          modules
11/16/2023  02:17 PM               132 MSG00001.bin
11/16/2023  02:20 PM    <DIR>          php-8.2.12-devel-vs16-x64
11/16/2023  02:33 PM           140,800 php.exe
11/16/2023  02:10 PM             1,318 php.exe.manifest
11/16/2023  02:33 PM             2,856 php.exe.res
11/16/2023  02:33 PM               871 php.exp
11/16/2023  02:33 PM             1,974 php.lib
11/16/2023  02:33 PM         5,059,584 php8ts.dll
11/16/2023  02:31 PM             2,003 php8ts.dll.def
11/16/2023  02:33 PM             1,100 php8ts.dll.res
11/16/2023  02:33 PM           316,699 php8ts.exp
11/16/2023  02:33 PM           507,148 php8ts.lib
11/16/2023  02:33 PM            57,856 php_sapnwrfc.dll
11/16/2023  02:10 PM             1,318 php_sapnwrfc.dll.manifest
11/16/2023  02:33 PM               924 php_sapnwrfc.dll.res
11/16/2023  02:33 PM               698 php_sapnwrfc.exp
11/16/2023  02:33 PM             1,850 php_sapnwrfc.lib
11/16/2023  02:33 PM           626,688 php_sapnwrfc.pdb
11/16/2023  02:31 PM    <DIR>          resp
11/16/2023  02:15 PM    <DIR>          sapi
08/14/2023  08:57 AM        19,795,968 sapnwrfc.pdb
11/16/2023  02:31 PM                93 tmp-php.ini
11/16/2023  02:32 PM    <DIR>          TSRM
11/16/2023  02:32 PM    <DIR>          win32
11/16/2023  02:17 PM               518 wsyslog.dbg
11/16/2023  02:17 PM                39 wsyslog.rc
11/16/2023  02:33 PM    <DIR>          Zend
              24 File(s)     26,640,557 bytes
              12 Dir(s)  134,003,728,384 bytes free

C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS
$ php -c tmp-php.ini

Warning: PHP Startup: Unable to load dynamic library 'php_sapnwrfc.dll' (tried: C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS\php_sapnwrfc.dll (The specified module could not be found), C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release
_TS\php_php_sapnwrfc.dll.dll (The specified module could not be found)) in Unknown on line 0

Any suggestions to go from here?

Some more information:
SAP NW RFC SDK 750 is located at C:\nwrfcsdk and the path is added as C:\nwrfcsdk\lib. The extension is also visible during configure:
Enabled extensions:
-----------------------
| Extension  | Mode   |
-----------------------
| date       | static |
| hash       | static |
| json       | static |
| pcre       | static |
| random     | static |
| reflection | static |
| sapnwrfc   | shared |
| spl        | static |
| standard   | static |
-----------------------

-----------------------------------------
|                     |                 |
-----------------------------------------
| Build type          | Release         |
| Thread Safety       | Yes             |
| Compiler            | Visual C++ 2019 |
| Target Architecture | x64             |
| Host Architecture   | x64             |
| Optimization        | PGO disabled    |
| Native intrinsics   | SSE2            |
| Static analyzer     | disabled        |
-----------------------------------------

**Comment by gkralik** [comment]
Can you try to debug with _ProcMon.exe_ from the _SysInternals_ suite to see which DLL the process cannot find?

I'll try to get a hold of a Windoes machine and see if I can reproduce.

**Comment by BjorgeSO** [comment]
I have not been able to run ProcMon.exe successfully in the docker container. I also tried the older guide found here: https://github.com/gkralik/php7-sapnwrfc/blob/07f6c6ef334660640ce5ee3e2f0c16afc0bb3ad1/docs/building.rst

It gave the same result, although it created a folder under /ext named sapnwrfc.

Directory of C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS
 
11/20/2023  09:50 AM    <DIR>          .
11/20/2023  09:50 AM    <DIR>          ..
11/20/2023  09:43 AM    <DIR>          devel
11/20/2023  09:38 AM           118,784 edit_a.pdb
11/20/2023  09:43 AM    <DIR>          ext
11/20/2023  09:50 AM                18 extension_dlls.txt
11/20/2023  09:44 AM    <DIR>          main
11/20/2023  09:43 AM               132 MSG00001.bin
11/20/2023  09:50 AM    <DIR>          php-8.2.12-devel-vs16-x64
11/20/2023  09:45 AM           140,800 php.exe
11/20/2023  09:37 AM             1,318 php.exe.manifest
11/20/2023  09:45 AM             2,856 php.exe.res
11/20/2023  09:45 AM               871 php.exp
11/20/2023  09:45 AM             1,974 php.lib
11/20/2023  09:45 AM         5,059,584 php8ts.dll
11/20/2023  09:43 AM             2,003 php8ts.dll.def
11/20/2023  09:37 AM             1,318 php8ts.dll.manifest
11/20/2023  09:45 AM             1,100 php8ts.dll.res
11/20/2023  09:45 AM           316,699 php8ts.exp
11/20/2023  09:45 AM           507,148 php8ts.lib
11/20/2023  09:45 AM            57,856 php_sapnwrfc.dll
11/20/2023  09:37 AM             1,318 php_sapnwrfc.dll.manifest
11/20/2023  09:45 AM               924 php_sapnwrfc.dll.res
11/20/2023  09:45 AM               698 php_sapnwrfc.exp
11/20/2023  09:45 AM             1,850 php_sapnwrfc.lib
11/20/2023  09:45 AM           626,688 php_sapnwrfc.pdb
11/20/2023  09:43 AM    <DIR>          resp
11/20/2023  09:43 AM    <DIR>          sapi
08/14/2023  08:57 AM        19,795,968 sapnwrfc.pdb
11/20/2023  09:43 AM                93 tmp-php.ini
11/20/2023  09:44 AM    <DIR>          TSRM
11/20/2023  09:44 AM    <DIR>          win32
11/20/2023  09:43 AM               518 wsyslog.dbg
11/20/2023  09:43 AM                39 wsyslog.rc
11/20/2023  09:45 AM    <DIR>          Zend
              24 File(s)     26,640,557 bytes
              11 Dir(s)  134,001,778,688 bytes free

I also got a folder in the ext folder liks this:
 Directory of C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS\ext\sapnwrfc

11/20/2023  09:43 AM    <DIR>          .
11/20/2023  09:43 AM    <DIR>          ..
11/20/2023  09:43 AM           458,503 exceptions.obj
11/20/2023  09:43 AM         2,694,247 exceptions.sbr
11/20/2023  09:43 AM           537,143 rfc_parameters.obj
11/20/2023  09:43 AM         2,712,648 rfc_parameters.sbr 
11/20/2023  09:43 AM           524,200 sapnwrfc.obj
11/20/2023  09:43 AM         2,722,534 sapnwrfc.sbr
11/20/2023  09:43 AM           446,911 string_helper.obj
11/20/2023  09:43 AM         2,687,245 string_helper.sbr
11/20/2023  09:43 AM           609,280 vc140.idb
               9 File(s)     13,392,711 bytes
               2 Dir(s)  134,001,778,688 bytes free

The generated php.ini file:
C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS
$ type tmp-php.ini
extension_dir=C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS 
extension=php_sapnwrfc.dll

Running "php -c tmp-php.ini" result in the same error as before:
Warning: PHP Startup: Unable to load dynamic library 'php_sapnwrfc.dll' (tried: C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release_TS\php_sapnwrfc.dll (The specified module could not be found), C:\php-sdk\phpdev\vs16\x64\php-src\x64\Release
_TS\php_php_sapnwrfc.dll.dll (The specified module could not be found)) in Unknown on line 0

I also tried using the ext library as library path in the ini file along with "nmake install" which also gave the error of the PHP build.

**Comment by BjorgeSO** [comment]
Read similar issue, and it looks like it was the Visual C++ Redistributable. As in the issue, I installed vc redist 2013. I tried with other redists found here:
https://download.visualstudio.microsoft.com/download/pr/9e04d214-5a9d-4515-9960-3d71398d98c3/1e1e62ab57bbb4bf5199e8ce88f040be/vc_redist.x64.exe

and here:
https://aka.ms/vs/17/release/vc_redist.x64.exe

None of which worked. Only the redist 2013 worked.
