### ISSUE TITLE
PHP 7.2 + SAP NW RFC 7.20 +php7-sapnwrfc 1.3.0 return parameter  is empty

### ISSUE THREAD

**Issue by cofeewll** [gkralik/php7-sapnwrfc#154]
**Question:**
Request for SAP rfc interface, successful return, but when the length of the returned parameter exceeds a certain length, the value returned by the invoke method is empty string.
Calling this interface from other development languages returns correct results.
**getFunction:**
![image](https://github.com/gkralik/php7-sapnwrfc/assets/11624358/540619a4-eac1-4eaf-a3c1-e713a97d4887)
**return:**
![image](https://github.com/gkralik/php7-sapnwrfc/assets/11624358/b56ba3eb-481c-439d-b257-aed48ef439c9)
This row of "ARKTX" data has the longest value and directly returns empty string, while other rows of data return normally.

What is the reason for this? Could you please help with the answer? Thank you very much

**Comment by gkralik** [comment]
Check if this also happens with the newest extension and SDK version.
