### ISSUE TITLE
Memory Leak Issue in SAP PHP Connection: Seeking Advice on Workaround

### ISSUE THREAD

**Issue by luckkas** [gkralik/php7-sapnwrfc#155]
## Overview
I am currently experiencing a memory leak issue in my SAP PHP connection when using the SAP functions "L_TO_CREATE_SINGLE" and "BAPI_GOODSMVT_CREATE." I have identified a workaround by adjusting the use_function_desc_cache option, and I am seeking advice from the community to better understand the root cause and explore potential improvements.

## Issue Details
* Environment: SAP NW RFC SDK version 7500.0.12 ,PHP version 8.2.12, Windows Server 2016 Standard version 1607 OS build 14393.6351
* The error message:
![ErrorMessageSAP](https://github.com/gkralik/php7-sapnwrfc/assets/123035794/bdcc8218-96ed-401f-bced-f6281b159e16)

* Workaround: I have found that setting the use_function_desc_cache option to false resolves the memory leaks. See the code snippet below:
``` 
$options = [
    'use_function_desc_cache' => false,
];

try {
    $this->con = new SAPNWRFC\Connection($parameters, $options);
    return $this->con;
} catch (Exception $e) {
    // Handle exceptions
} 
```
## Related Issues
- This issue is related to #119 
- My workaround is related to #136

## Request for Assistance
I am seeking advice on why this workaround solves the issue and whether there are better approaches to address memory leaks in SAP PHP connections. Any insights or suggestions from the community would be greatly appreciated.

**Comment by pieewiee** [comment]
This problem was driving me nuts. Thank you!!!

**Comment by dbielke1986** [comment]
We have the same issue here. We need to set 'use_function_desc_cache' => false; otherwise we have a fatal error.
I will follow this issue.

**Comment by gkralik** [comment]
I am investigating this, although I haven't been able to reproduce yet.

**Comment by gkralik** [comment]
Some questions:
- does this appear only in long-running PHP scripts or one-off scripts as well?
- where exactly does the overflow happen? `getFunction()`, `invoke()`, ...?

Also, @pieewiee & @dbielke1986 can you share your environment (SDK version, extension version, OS, 32/64bit).

And if anyone can test that with the latest SDK version and the latest code of the extension, that would help a lot (function desc cache related change post 2.0.0 - probably unrelated, but who knows)...

**Comment by gkralik** [comment]
@dbielke1986 OK, this sounds a little different.

If the parameters of an RFC change while your script is running, you have to either disable the function description cache completely (`use_function_desc_cache`) or clear the cache manually.

If you get an error every second call, try the latest version of the extension *in the repository* (especially including e649a80efaa1fd92e9f30f83a27ecd14795417c1). This fixes a problem with repeated calls of the same RFC, especially when the `RemoteFunction` object is freed (unset, variable reused).

**Comment by gkralik** [comment]
Also, can you reproduce the issue with a generic RFC call (like `RFC_PING`, `STFC_STRUCTURE`) and if so, can you share a code snippet? This way I can try to debug this.

**Comment by dbielke1986** [comment]
@gkralik 

I will try to test this with [e649a80](https://github.com/gkralik/php7-sapnwrfc/commit/e649a80efaa1fd92e9f30f83a27ecd14795417c1) and give some feedback.

Thanks for your help and this absolutely incredibly helpful module (essential for us and our use case)!

**Comment by gkralik** [comment]
I have drafted a new release [2.1.0](https://github.com/gkralik/php7-sapnwrfc/releases/tag/2.1.0), if that helps with testing.

**Comment by dbielke1986** [comment]
@gkralik 

We have updated our page to 2.1.0 + SAP SDK 750 PL13 and everything seems to work right now. Even with `use_function_desc_cache = true` . 

I will monitor this issue for a few more days and then give feedback again.
So far, however, everything looks great. Many, many thanks for the module and fixing the problem!

**Comment by gkralik** [comment]
@dbielke1986 has the issue emerged again or is everything working for you now?

**Comment by dbielke1986** [comment]
@gkralik:

Everything is working great! The mentioned fix solves our issue with daily use and hundreds of calls a day.
Thank you so much for you fast reply and the quick fix you provided!
