### ISSUE TITLE
Error building PHP Version: 8.3.3 with sap nw rfc 7.5 patch 12

### ISSUE THREAD

**Issue by drb2016** [gkralik/php7-sapnwrfc#156]
PHP version: 8.3.3
SAP NW RFC version: 7.5 patch 12 (the latest patch, SAP doesn't provide old versions of patch)

When i execute the **nmake** command to build the extension, the following errors appear:

rfc_parameters.obj : error LNK2001: unresolved external symbol RfcSetInt8
rfc_parameters.obj : error LNK2001: unresolved external symbol RfcGetInt8
C:\PHP\php-sdk\phpdev\vs16\x64\php-8.3.3-src\x64\Release\php_sapnwrfc.dll : fatal error LNK1120: 2 unresolved externals
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\link.exe"' : return code '0x460'
Stop.

![image](https://github.com/gkralik/php7-sapnwrfc/assets/22154343/9fc8e3c3-0424-4fe4-9849-e595852bb287)

**Comment by gkralik** [comment]
Are you sure the SDK is in the path?
