### ISSUE TITLE
please release php_sapnwrfc.dll for PHP 8.3.8

### ISSUE THREAD

**Issue by tamanoon** [gkralik/php7-sapnwrfc#158]
### Question

please release php_sapnwrfc.dll for PHP 8.3.8 

Thnak you so much.

**Comment by gkralik** [comment]
` php_sapnwrfc-2.1.0+php.8.3.7-nts-vs16-x64.sdk.7500.0.13.dll ` and ` php_sapnwrfc-2.1.0+php.8.3.7-vs16-x64.sdk.7500.0.13.dll ` should work just fine. If not, you can always build the extension yourself.

I do not have the time to provide Windows builds for all PHP releases.
