### ISSUE TITLE
Connect to a message server (Load Balancing)

### ISSUE THREAD

**Issue by FlorinProfeanu** [gkralik/php7-sapnwrfc#159]
Hello,

Is it possible to connect to a message server (Load Balancing)?

Florin

**Comment by gkralik** [comment]
See [Connecting to a SAP System](https://gkralik.github.io/php7-sapnwrfc/usage.html#connecting-to-a-sap-system), specifically the link to the _sapnwrfc.ini_ parameters.

**Comment by FlorinProfeanu** [comment]
Hello,

I am trying to see if the setup pf ini file works also when using ashost. Then I will see how to manage balancing server.

This works:
$config = [
  'ashost' => 'my_host',
  'sysnr'  => 'my_sysnr',
  'client' => 'my_client',
  'user'   => 'my_user',
  'passwd' => 'my_password',
];
$sapConnection = new SapConnection($config)

So I created a sapnwrfc.ini in the same folder with my PHP script:
ASHOST=my_host
SYSNR=my_sysnr
CLIENT=my_client
USER=my_user
PASSWD=my_password

Then I do this:
SAPNWRFC\Connection::setIniPath("sapnwrfc.ini");

The question is: how I write this when using ini file?
$sapConnection = new SapConnection(????); 

I want also to mention that the call to setIniPath does not fail, even if the file name mentioned as parameter does not exist.

Florin

**Comment by gkralik** [comment]
1. `SAPNWRFC\Connection::setIniPath()` takes a path where the SDK searches for the INI file, not the path to the file itself. It will not error if the path or file does not exist, simply because the SDK itself does not seem to care.
2. For connecting to a system entry defined in the INI file, just use the `DEST` parameter (see below):

```ini
DEST=test
ASHOST=<YOUR_HOST>
SYSNR=00
CLIENT=<YOUR_CLIENT<
USER=<USER>
PASSWD=<PWD>
TRACE=0
```

```php
<?php

SAPNWRFC\Connection::setIniPath(__DIR__); // for an INI file in the same directory as the script
$connection = new SAPNWRFC\Connection([ 'DEST' => 'test']);

// Do stuff here...
```

I made a not to improve the documentation and provide an example.

**Comment by FlorinProfeanu** [comment]
The call  _**SAPNWRFC\Connection::setIniPath(__DIR__)**_  saved the day, thank you so much.
Now is all good, including using MSHOST for balancing server. MSSERV was not needed in my case.
