### ISSUE TITLE
0.7.0 release

### ISSUE THREAD

**Issue by ThaDafinser** [gkralik/php7-sapnwrfc#16]
Please tell me when all is commited to master/develop for the 0.7.0 release.

Then i will build again for windows...i think that release should be already pretty stable.
At least in my cases

**Comment by gkralik** [comment]
I plan to do most of the work tonight. I absolutely want to finish the tests and fix the parameter status issue (active/inactive). I'll ping as soon as it's done.

**Comment by gkralik** [comment]
The next release is nearly finished. Should be ready tonight. I'll ping you @ThaDafinser as soons as I'm done.

**Comment by ThaDafinser** [comment]
Great thing! Will be happy to build all 4 windows releases again

**Comment by ThaDafinser** [comment]
@gkralik just fetched the latest master and build one.

Currently there is one warning in VS2015

![image](https://cloud.githubusercontent.com/assets/533017/13390306/defa9e80-decd-11e5-9a4d-3dfb1a70df4d.png)

**Comment by gkralik** [comment]
@ThaDafinser I release 0.7.0. If you can provide builds, I will attach them to the release. Many thanks in advance.

**Comment by ThaDafinser** [comment]
@gkralik I cannot add the files to an issue or PR (as "text)

I would either need to create a fake PR, or you add me as a contrib, so i can edit the release and add it directly.

What u pref longterm? Maybe you have another idea?

**Comment by gkralik** [comment]
I haven't really thought about it yet. For now, create a fake PR and I'll
think about a better way to handle this...
