### ISSUE TITLE
Change trace directory and level at runtime

### ISSUE THREAD

**Issue by ThaDafinser** [gkralik/php7-sapnwrfc#17]
https://scn.sap.com/thread/1822094

To change the `trace` dir, i've done this ugly thing in the PHP5 extension
```php
        $cwd = getcwd();
        chdir('../my-log-dir');
        try {
            $conn = new sapnwrfc($options);
        } finally {
            chdir($cwd);
        }
```

Maybe adding the `RfcResetTraceDir` makes sense?

**Comment by gkralik** [comment]
Yes, I plan to add methods for setting the trace dir and level. It is on my TODO list :smile:
