### ISSUE TITLE
TRACE_LEVEL_OFF does create minimal trace file?

### ISSUE THREAD

**Issue by gkralik** [gkralik/php7-sapnwrfc#21]
Setting the trace level to `TRACE_LEVEL_OFF` should disable trace files entirely.
Check if that is the case or if it is a bug (in the extension or upstream).

**Comment by gkralik** [comment]
In my tests, this works as excpected and intended (test `087` covers this case).
What I notice is a `dev_rfc.trc` file which is even created when tracing is disabled. That file just tells me that I have to install `uuidd`. One can't seem to get rid of those files without fixing the error in it.

**Comment by gkralik** [comment]
@ThaDafinser is it the same for you or do you get another trace file? If yes, can you provide me a minimal code example to reproduce?

**Comment by ThaDafinser** [comment]
@gkralik looks good, let's go to `v1.0` :smile: 

Found the problem on my side....i added trace again in the config :see_no_evil: 
```php
use SAPNWRFC\Connection as SapConnection;

SapConnection::setTraceLevel(SapConnection::TRACE_LEVEL_OFF);


$config = [
    // options
    'TRACE' => true,
];
try {
    $conn = new SapConnection($config);
} catch(\Exception $ex){
    
}

var_dump($conn->ping());
```
