### ISSUE TITLE
Publish on PECL

### ISSUE THREAD

**Issue by ThaDafinser** [gkralik/php7-sapnwrfc#23]
Since this extension is well tested and many people need SAP access, i think the visibility of this project needs to be better.

Most people will search for extensions over pecl, so i think this would be a good place to list this extension
https://pecl.php.net/account-request.php

Currently you can only find it, if you directly search it on github or google around a while

**Comment by gkralik** [comment]
I'll look into that next week.

**Comment by avadaneidanut** [comment]
@gkralik reminder on this one. Is something that we can do to help you with this?

**Comment by gkralik** [comment]
Ah thanks, I had almost forgotten about this one.
I'll have to apply for a PECL account to be able to publish the extension. I'll have a look as soon as I have some spare time.

**Comment by gkralik** [comment]
I'm still thinking about a way to streamline the Windows build experience before I'm willing to take this step. And we would have to make some CS fixes to comply with the PHP coding standard...

**Comment by ThaDafinser** [comment]
CS fixes shouldnt be a problem.
For the windows builds the SAP lib is required which might be a license issue (will be published on pecl for the automatic builds)

Maybe in the first step unix only would be enough

**Comment by gkralik** [comment]
The SAP NW RFC lib is needed for all builds. And we are definitely not publishing it, as that would be a blatant violation of the license.
So even if we publish on PECL, a user would be required to first obtain and extract the library before being able to install the extension.

**Comment by ThaDafinser** [comment]
For automatic build, the SAP package is required (if i'm not wrong).

PECL is currently publishing all dependencies here: http://windows.php.net/downloads/pecl/deps/

I asked for permission some time ago at SAP here: https://archive.sap.com/discussions/thread/3862034

**Comment by gkralik** [comment]
There won't be any fully automated builds for this extension. I see no way
whatsoever to get permission to redistribute.

The only way is to manually download the lib and extract it before
attempting to build the extension.

**Comment by gkralik** [comment]
Building the extension is reasonably easy provided one has the SAP NW RFC SDK installed. Publishing on PECL would only make sense if the build could be fully automated and that would require permission to redistribute the SDK. It's unlikely we will get the permission, so closing this.
