### ISSUE TITLE
Connect via SAP Router

### ISSUE THREAD

**Issue by julianz85** [gkralik/php7-sapnwrfc#24]
Hi, is there a way to specify connection over sap router?
Thanks
Alan

**Comment by gkralik** [comment]
Put your saprouter string in `ashost`:

```php
$conn = new \SAPNWRFC\Connection([
  'ashost' => '/H/your.saprouter.local/H/your.system.local',
  // ...
]);
```

**Comment by volshebnikRAJ** [comment]
Hello, I've tried using this and it doesn't work. Can you please help me
