### ISSUE TITLE
Extra spaces being added to all return values it seems

### ISSUE THREAD

**Issue by studio2222** [gkralik/php7-sapnwrfc#25]
Hi guys!

Stellar job on this php 7 release of the connector. What a lifesaver.

I'm noticing, however, when comparing results to the connector we were using before this, to this connector, that spaces are being added to the end of nearly all values, bot scalar and in table results.

Example:
Call function:
BAPI_CUSTOMER_GETDETAIL1

With import params:
CUSTOMERNO = 2000xxxxx customer number
PI_SALESORG = 33xx 

Look at field 'NAME' in result table PE_COMPANYDATA

The value you'll see seems to be padded with spaces (possibly to match the datatype of the field): "ABC Company Inc.          ".  

This causes us to have to unfortunately trim every value (both scalar and in tables) coming back, which is undesirable from a performance, coding, and bug-management perspective (sometimes we may forget to do this in instances and the bug will slip through).

**Comment by ThaDafinser** [comment]
This is the returned valued from SAP (i guess). That was also the behaviour in the PHP5 extension.

If i'm not wrong, SAP always fill the fields with whitespaces to the defined length of the column.

**Comment by avadaneidanut** [comment]
@ThaDafinser I also think you are right.

@studio2222 Think of the following scenario, you receive a GUID from SAP result that is always 16 bytes long. After applying a recursive trim over all the array (I always did this to remove unused spaces) sometimes the last character of a GUID is a space, end of line or carriage return (happens) and you mess up the data. I lost many hours trying to figure out where I was wrong and it was the trimming.

**Comment by studio2222** [comment]
Yeah these 90/10 scenarios are tough.  Previously we were using the saprfc connector which auto trimmed, and we detected this difference when comparing old version new results. However since it seems that 90% of the time trimming the values  is more helpful and harmful, would you be ok adding a configuration setting that would turn trimming on? Say as part of the call function method or as maybe a global setting you can turn on/off?

**Comment by ThaDafinser** [comment]
:-1:  for a configuration - this could lead to accidental errors like told by @avadaneidanut 

Better an extra function, which does this job

**Comment by gkralik** [comment]
I'll look into this after my holiday...

**Comment by gkralik** [comment]
Back from holiday...

Initially, I planned to provide an option to automatically trim returned values. But the more I think about it, the less I think this would be good or the right way.

The developer should know what kind of values/data types to expect to be returned from SAP and therefore should decide whether to trim or not on a per item base. Letting the extension do the trimming just hides the fact that SAP has different data types, padding, etc. - and in my experience, such magic causes bugs.

Also, I would not be sure where to add an option for auto-trimming:
1. Setting a global option does not feel right, as it might not be obvious which setting is effective at the time of calling an RFC.
2. Adding a parameter to `invoke()` might work, though.

Using 2) might work, up until the time where you have RFCs that return complex and/or nested structures/tables where you would want one member to be trimmed, but not the other. So you end up doing the trimming manually anyways.

Personally, I use `trim()` manually on every item that I want to be trimmed. That way, I make the decision an explicit one and I always know the data I am handling.

**Comment by studio2222** [comment]
Ok, agreed. Not the end of the world. I've added code to trim all values coming back.
