### ISSUE TITLE
Failed to set TABLE row, expected array

### ISSUE THREAD

**Issue by studio2222** [gkralik/php7-sapnwrfc#26]
We've been wrestling with this one a bit - am getting message "Failed to set TABLE row, expected array"  when calling BAPI_SALESORDER_CREATEFROMDAT2. It would be great if in a downstream version -- if possible -- the error message could include which table parameter it is complaining about. There are a bunch of tables for this BAPI and we're having a hard time figuring out which is the offending item  : )

We're calling BAPI_SALESORDER_CREATEFROMDAT2 with the following data:
 
```
            [ORDER_HEADER_IN] => Array
                (
                    [DOC_TYPE] => Y0OR
                    [SALES_ORG] => 3310
                    [DISTR_CHAN] => 00
                    [DIVISION] => 00
                    [PURCH_NO_C] => 
                    [COLLECT_NO] => 
                )

            [ORDER_PARTNERS] => Array
                (
                    [0] => Array
                        (
                            [PARTN_ROLE] => AG
                            [PARTN_NUMB] => 0020040938
                        )

                )

            [ORDER_ITEMS_IN] => Array
                (
                    [0] => Array
                        (
                            [ITM_NUMBER] => 00010
                            [MATERIAL] => BC535R
                        )

                    [1] => Array
                        (
                            [ITM_NUMBER] => 00020
                            [MATERIAL] => B0020017
                        )

                    [2] => Array
                        (
                            [ITM_NUMBER] => 00030
                            [MATERIAL] => B0020017
                        )

                )

            [ORDER_CONDITIONS_IN] => Array
                (
                    [0] => Array
                        (
                            [ITM_NUMBER] => 00020
                            [COND_TYPE] => Y0M1
                            [COND_VALUE] => 11.111
                        )

                )

            [ORDER_TEXT] => Array
                (
                    [0] => Array
                        (
                            [TEXT_ID] => Y004
                            [LANGU] => EN
                            [FORMAT_COL] => *
                            [TEXT_LINE] => 
                        )

                )

            [ORDER_SCHEDULES_IN] => Array
                (
                    [0] => Array
                        (
                            [ITM_NUMBER] => 00010
                            [REQ_QTY] => 1
                        )

                    [1] => Array
                        (
                            [ITM_NUMBER] => 00020
                            [REQ_QTY] => 2
                        )

                    [2] => Array
                        (
                            [ITM_NUMBER] => 00030
                            [REQ_QTY] => 1
                        )
                )
        )
```

The interface is listed here fyi:
http://www.se80.co.uk/sapfms/b/bapi/bapi_salesorder_createfromdat2.htm

ORDER_HEADER_IN is an is an EXPORTING structure. The rest are TABLES parameters. Thus I can't seem to figure out whats wrong : (

Ran a full trace -- doesn't seem to suggest the location of the issue?

![image](https://cloud.githubusercontent.com/assets/20129411/18483727/595c40e0-79b3-11e6-9390-2a61df5ae0db.png)

**Comment by gkralik** [comment]
The error messages are indeed not ideal, I'll have a look at improving them. Most of them already state the parameter name when an error occurs, but some of the TABLE methods do not currently.

The `RFC_ILLEGAL_STATE` return code in `RfcDestroyFunctionDesc` should not be an issue. There's definitely a problem worth investigating there, but I think your problem lies somewhere else.

I'll have a look at the BAPI. I'm using it in one of my projects, so I should find a clue...

**Comment by gkralik** [comment]
Can you upload the full trace somewhere (make sure to whipe credentials and the like)?

**Comment by studio2222** [comment]
You bet - thanks much for the help. Here you go.
[rfc09564_09388.salesorder.usb.failed.txt](https://github.com/gkralik/php7-sapnwrfc/files/470797/rfc09564_09388.salesorder.usb.failed.txt)

**Comment by gkralik** [comment]
Actually, I can't reproduce your error. Using this code:

```php
<?php

$config = include "tests/sapnwrfc.config.inc";

$c = new \SAPNWRFC\Connection($config);

$f = $c->getFunction('BAPI_SALESORDER_CREATEFROMDAT2');
$r = $f->invoke([
    'ORDER_HEADER_IN' => [
                'DOC_TYPE' => 'Y0OR',
                'SALES_ORG' => '3310',
                'DISTR_CHAN' => '00',
                'DIVISION' => '00',
                'PURCH_NO_C' => '',
                'COLLECT_NO' => '',
    ],
    'ORDER_PARTNERS' => [
        [
            'PARTN_ROLE' => 'AG',
            'PARTN_NUMB' => '0020040938',
        ]

    ],
    'ORDER_ITEMS_IN' => [
        [
            'ITM_NUMBER' => '00010',
            'MATERIAL' => 'BC535R',
        ],
        [
            'ITM_NUMBER' => '00020',
            'MATERIAL' => 'B0020017',
        ],
        [
            'ITM_NUMBER' => '00030',
            'MATERIAL' => 'B0020017',
        ]
    ],
    'ORDER_CONDITIONS_IN' => [
        [
            'ITM_NUMBER' => '00020',
            'COND_TYPE' => 'Y0M1',
            'COND_VALUE' => 11.111,
        ]
    ],
    'ORDER_TEXT' => [
        [
            'TEXT_ID' => '004',
            'LANGU' => 'EN',
            'FORMAT_COL' =>'*',
            'TEXT_LINE' => '',
       ]
    ],
    'ORDER_SCHEDULES_IN' => [
        [
            'ITM_NUMBER' => '00010',
            'REQ_QTY' => 1.0,
        ],
        [
            'ITM_NUMBER' => '00020',
            'REQ_QTY' => 2.0
        ],
        [
            'ITM_NUMBER' => '00030',
            'REQ_QTY' => 1.0
        ]
    ]
]);

var_dump($r);
```

I only get errors about the sales document not existing, etc. (which was expected), but the source line that produces the error you mentioned executes cleanly.

I'll poke around a little more though. Can you show me a code snippet that reliably reproduces the error for you?

**Comment by studio2222** [comment]
Thanks I'll try your code snippet in the morning and get back to you. Best,




On Wed, Sep 14, 2016 at 2:03 AM -0400, "Gregor Kralik" <notifications@github.com<mailto:notifications@github.com>> wrote:


Actually, I can't reproduce your error. Using this code:

<?php

$config = include "tests/sapnwrfc.config.inc";

$c = new \SAPNWRFC\Connection($config);

$f = $c->getFunction('BAPI_SALESORDER_CREATEFROMDAT2');
$r = $f->invoke([
    'ORDER_HEADER_IN' => [
                'DOC_TYPE' => 'Y0OR',
                'SALES_ORG' => '3310',
                'DISTR_CHAN' => '00',
                'DIVISION' => '00',
                'PURCH_NO_C' => '',
                'COLLECT_NO' => '',
    ],
    'ORDER_PARTNERS' => [
        [
            'PARTN_ROLE' => 'AG',
            'PARTN_NUMB' => '0020040938',
        ]

    ],
    'ORDER_ITEMS_IN' => [
        [
            'ITM_NUMBER' => '00010',
            'MATERIAL' => 'BC535R',
        ],
        [
            'ITM_NUMBER' => '00020',
            'MATERIAL' => 'B0020017',
        ],
        [
            'ITM_NUMBER' => '00030',
            'MATERIAL' => 'B0020017',
        ]
    ],
    'ORDER_CONDITIONS_IN' => [
        [
            'ITM_NUMBER' => '00020',
            'COND_TYPE' => 'Y0M1',
            'COND_VALUE' => 11.111,
        ]
    ],
    'ORDER_TEXT' => [
        [
            'TEXT_ID' => '004',
            'LANGU' => 'EN',
            'FORMAT_COL' =>'*',
            'TEXT_LINE' => '',
       ]
    ],
    'ORDER_SCHEDULES_IN' => [
        [
            'ITM_NUMBER' => '00010',
            'REQ_QTY' => 1.0,
        ],
        [
            'ITM_NUMBER' => '00020',
            'REQ_QTY' => 2.0
        ],
        [
            'ITM_NUMBER' => '00030',
            'REQ_QTY' => 1.0
        ]
    ]
]);

var_dump($r);

I only get errors about the sales document not existing, etc. (which was expected), but the source line that produces the error you mentioned executes cleanly.

I'll poke around a little more though. Can you show me a code snippet that reliably reproduces the error for you?

-

**Comment by gkralik** [comment]
I updated the exception messages to be more clear.

Consider this code, passing a wrong parameter type to `ORDER_PARTNERS`:

```php
// [...]
$r = $f->invoke([
   // [...]
    'ORDER_PARTNERS' => [
            // ORDER_PARTNERS is a table, but we are not passing rows here
            'PARTN_ROLE' => 'AG',
            'PARTN_NUMB' => '0020040938',
    ],
  // [...]
]);

// [...]
```

Instead of only
 `Failed to set TABLE row, expected array`
the message is now
  `Failed to set TABLE row, expected array for parameter ORDER_PARTNERS`

I'll release a new version in the next days, so @ThaDafinser can (hopefully?) provide new builds for Windows.

**Comment by gkralik** [comment]
Happy to hear it works.

I'll definitely have a look at why it doesn't work with references though. I rarely use them, so there are no test using references that could have caught this issue. I'll open another ticket to track progress...

**Comment by szabizs** [comment]
So the problem with this is that you have to define an array, but watch out how you define it

This will not work because the array does not have an **index**.
`		$customersData = [
			'LOW'       =>  $sap->populateKunnrWithZeros($customer->kunnr),
			'HIGH'      =>  $sap->populateKunnrWithZeros($customer->kunnr)
		];`

This will work because the array has an **index**.
`		$customersData[0] = [
			'LOW'       =>  $sap->populateKunnrWithZeros($customer->kunnr),
			'HIGH'      =>  $sap->populateKunnrWithZeros($customer->kunnr)
		];`
