### ISSUE TITLE
Windows builds for 1.1.1

### ISSUE THREAD

**Issue by gkralik** [gkralik/php7-sapnwrfc#29]
@ThaDafinser could you provide Windows builds for the latest release 1.1.0?

**Comment by ThaDafinser** [comment]
@gkralik it seems that the version increase is missing. Just did a build and version is still `1.0.0`

**Comment by ThaDafinser** [comment]
https://github.com/gkralik/php7-sapnwrfc/blob/master/php_sapnwrfc.h#L16

**Comment by gkralik** [comment]
Ups... I'll update it to 1.1.1 and ping you as soon as it's done...

**Comment by gkralik** [comment]
Version 1.1.1 is pushed, should be OK now...

**Comment by ThaDafinser** [comment]
@gkralik i uploaded the new builds for `1.1.1` here
https://github.com/ThaDafinser/php7-sapnwrfc

***Note that this time i only did x64 builds.***
Since i don't believe that someone really uses x86. If someone complains for missing builds, we can add them then.

**Comment by gkralik** [comment]
Thanks a lot. I attached the build to the [1.1.1 release page](https://github.com/gkralik/php7-sapnwrfc/releases/tag/1.1.1).

I agree with only providing x64 builds. If someone really needs x86, they can build themselves as we provide build instruction anyway.
