### ISSUE TITLE
Idea: Exception interface

### ISSUE THREAD

**Issue by ThaDafinser** [gkralik/php7-sapnwrfc#3]
Create a exception interface, which is extended by `ConnectionException` and `FunctionCallException` so you can catch both Exceptions with one try/catch

```php
try {
    $c = new \SAPNWRFC\Connection([
        'ashost' => 'my.sap.system.local',
        'sysnr'  => '00',
        'client' => '123',
        'user' => 'DEMO',
        'passwd' => 'XXXX',
        'trace'  => '0'
    ]);

    $f = $c->getFunction('Z_TEST_FUNCTION');
    $result = $f->invoke([
        'CHAR1' => 'A',
        'TABL' => [
            ['INT4' => 1, 'CHAR4' => 'NOPE'],
        ]
    ]);

    var_dump($result);
} catch(\SAPNWRFC\ExceptionInterface $ex) {
    // do something
}
```

**Comment by gkralik** [comment]
If you look into docs/api.md there is `\SAPNWRFC\Exception` as a parent class to both `ConnectionException` and `FunctionCallException`. I added this yesterday. It's not an interface, but should serve the same purpose. What do you think?

**Comment by ThaDafinser** [comment]
Yeah that's fine too.

I saw it, but thought it's a new one and the other extends the "PHP default" exception.
