### ISSUE TITLE
When SAP return a big array, error happen.

### ISSUE THREAD

**Issue by bmoif** [gkralik/php7-sapnwrfc#30]
Hello sir!
I meet a problem when submit a form.
we have a sales report in SAP, which have many selection options. if we input more condition, we'll get less result,else we'll get huge result. In SAP, everything works fine. But when I submit a form with very less selection condition(ex. S_month: 01 - 10), error happen like this:
```Failed to invoke function ZFIR010 in /php/wwwroot/others/saperp/index/zsap_zfir010.php:69
Stack trace:
#0 /php/wwwroot/others/saperp/index/zsap_zfir010.php(69): SAPNWRFC\RemoteFunction->invoke(Array)
#1 {main} thrown in /php/wwwroot/others/saperp/index/zsap_zfir010.php on line 69```

is the rfc interface has limite?

could you help, thanks!

**Comment by gkralik** [comment]
Please turn on tracing and run the failing code again. Then attach the trace file (make sure to redact confidential information).

**Comment by bmoif** [comment]
Category               ABAP Programming Error
Runtime Errors         CALL_FUNCTION_SEND_ERROR
ABAP Program           SAPLZ_WX_SD_GROUP01
Application Component  Not assigned
Date and Time          2016.10.27 20:42:26

**Short Text**
    " " (I/O error)

**What happened?**
    CPIC-CALL: 'ThCMSEND', communication rc: CM_DEALLOCATED_NORMAL (cmRc=18),
     taskhandler rc: SAP_O_K (thRc=0)#统计不活动
    An error occurred while making a Remote Function Call.

**Error analysis**
    An error occurred while making a Remote Function Call.

    CPIC-CALL: 'ThCMSEND', communication rc: CM_DEALLOCATED_NORMAL (cmRc=18),
     taskhandler rc: SAP_O_K (thRc=0)#static not active

    State of connection.. CODE=CM_DEALLOCATED_NORMAL CM_SEND_RECEIVED
     CM_COMPLETE_DATA_RECEIVED  SAPCODE=0  CONV=02687074
    Internal error code... "RFC_IO5"
    There is an error in the communication system. To clarify and resolve
    the error, contact your system administrator.

**Internal notes**
    The termination was triggered in function "jfunc_back" of the SAP kernel, in
    line 8589 of module "//bas/742_STACK/src/krn/abap/runt/abfunc.c#2".
    The internal operation just processed is "FUNC".
    Internal mode started at 20161027204226.
    Connection description: "IO HANDLE=1 DRV=INT LINE=4015 CODE=5 : GET ID=ffff
     LINE=0 CODE=0 : PUT ID=4004 LINE=145 "

**Comment by bmoif** [comment]
it seems php memory overflow....

**Comment by gkralik** [comment]
Have you tried using `memory_get_usage()`? What's your `memory_limit` setting?

**Comment by bmoif** [comment]
yes, trid that. memory_get_usage() usually less than 1M. memory_limit = 521M.
I tried the same code with java (jco). No problem!

**Comment by gkralik** [comment]
I haven't been able to reproduce this issue locally.

Have you tried `memory_get_peak_usage()`?

**Comment by gkralik** [comment]
Can you show me the detailed exception output when the function call fails?

```php
try {
    $c = new \SAPNWRFC\Connection($config);
    $f = $c->getFunction('YOUR_FUNCTION');
    $f->invoke([/* your params*/]);
    
    echo "peak usage: " . (int)memory_get_peak_usage(true) ."\n";
    
    echo "ok\n";
} catch(\SAPNWRFC\FunctionCallException $e) {
    echo "failed: {$e->getMessage()}\n";
    print_r($e);
}
```

I'm especially interested in the `errorInfo` property of the exception object.

**Comment by bmoif** [comment]
**I get the following error infomation:**
SAPNWRFC\FunctionCallException Object
(
    [message:protected] => Failed to invoke function zfir001
    [string:Exception:private] => 
    [code:protected] => 22
    [file:protected] => /index/zfir001.php
    [line:protected] => 79
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => /index/zfir001.php
                    [line] => 79
                    [function] => invoke
                    [class] => SAPNWRFC\RemoteFunction
                    [type] => ->
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [P_VKORG] => 1000
                                    [P_GJAHR] => 2016
                                    [S_MONATLOW] => 01
                                    [S_MONATHIGH] => 06
                                    [S_BZIRK] => 
                                    [S_VKBUR] => 
                                    [S_SPART] => 
                                    [P_RPSTA] => 4000000000
                                )

                        )

                )

        )

    [previous:Exception:private] => 
    [errorInfo:protected] => Array
        (
            [code] => 22
            [key] => RFC_CONVERSION_FAILURE
            [message] => Could not convert from 4110 codepage to 4103 codepage, rc = 512
        )

)

**Comment by bmoif** [comment]
I have tried the following, but it didn't work. I think the main reason might be SAP
return too many data, and php array can't process so many data, the error happens.
because if I limit the [S_MONATLOW] and [S_MONATHIGH] like 01 - 03, it works.
if 01-04 (means more data return from SAP than contition 01-03), error happens.
if 04 -04 , it works……
https://archive.sap.com/discussions/thread/1857186

DCP = 4110
UCP = 4110

**Comment by ThaDafinser** [comment]
@bmoif the error msg states something about the codepage (encoding)
> Could not convert from 4110 codepage to 4103 codepage, rc = 512

So it seems not to be the size

**Comment by gkralik** [comment]
Yes, it seems to be an error on the ABAP side, not PHP. I have tested with large array and never had any problems.

I'll have another more detailed look in the next few days though...

**Comment by bmoif** [comment]
but if it is about encoding, if I submit php with  [S_MONATLOW] and [S_MONATHIGH] like 01 -01, it works.

ST22 error info:
-----------------------------
Category               ABAP Programming Error
Runtime Errors         CALL_FUNCTION_SEND_ERROR
ABAP Program           SAPLZ_WX_SD_GROUP01
Application Component  Not assigned
Date and Time          2016.11.18 16:13:38

Short Text
    " " (I/O error)

What happened?
    CPIC-CALL: 'ThCMSEND', communication rc: CM_DEALLOCATED_NORMAL (cmRc=18),
     taskhandler rc: SAP_O_K (thRc=0)#state not active

    An error occurred while making a Remote Function Call.
	
Error analysis
    An error occurred while making a Remote Function Call.

    CPIC-CALL: 'ThCMSEND', communication rc: CM_DEALLOCATED_NORMAL (cmRc=18),
     taskhandler rc: SAP_O_K (thRc=0)#state not active

    State of connection.. CODE=CM_DEALLOCATED_NORMAL CM_SEND_RECEIVED
     CM_COMPLETE_DATA_RECEIVED  SAPCODE=0  CONV=87617125
    Internal error code... "RFC_IO5"
    There is an error in the communication system. To clarify and resolve
    the error, contact your system administrator.

**Comment by bmoif** [comment]
@ThaDafinser I tested again, maybe it really caused by the encoding!!

for example:
we have 1073 entries in SAP ECC for condition [S_MONATLOW] and [S_MONATHIGH] =(03,03). but if I submit with this condition, it works well.

we have 1268 entries in SAP ECC for condition [S_MONATLOW] and [S_MONATHIGH] =(06,06). if I submit with this condition, error happen.
[errorInfo:protected] => Array
        (
            [code] => 22
            [key] => RFC_CONVERSION_FAILURE
            [message] => Could not convert from 4110 codepage to 4103 codepage, rc = 512
        )

we have 712 entries in SAP ECC for condition [S_MONATLOW] and [S_MONATHIGH] =(04,04). if I submit with this condition, error happen.
[errorInfo:protected] => Array
        (
            [code] => 22
            [key] => RFC_CONVERSION_FAILURE
            [message] => Could not convert from 4110 codepage to 4103 codepage, rc = 2048
        )

we have 1489 entries in SAP ECC for condition [S_MONATLOW] and [S_MONATHIGH] =(02,03). if I submit with this condition, it works well.

so, this encoding might be the real reason...

**Comment by gkralik** [comment]
Seeing this numbers I'm convinced it is an encoding issue. I have tested with some 10.000 returned rows without a problem.

**Comment by bmoif** [comment]
do you have any suggestion for this? 

based on the msg([message] => Could not convert from 4110 codepage to 4103 codepage, rc = 2048)
it seems we have two kind of encoding in SAP, but the php file's encoding is utf8.

CODEPAGE              = '4110' "UTF-8 
CODEPAGE              = '4103' "UTF-16

**Comment by gkralik** [comment]
Sadly, I have no suggestion...ö
