### ISSUE TITLE
PHP <-> SAP Write Values

### ISSUE THREAD

**Issue by RaphaelHerd** [gkralik/php7-sapnwrfc#31]
Hi,

at first I would like to thank you for your work. The code works great. The reason why I'm posting an issue is that I'm not sure if my problem is related to your SAP wrapper or if it's a conceptual problem.

The problem I have is that I cannot write to SAP. It seems that all parameters (user credentials, permission, etc.) are set correct. I also can use the ping-test and some other functions that return data from SAP.
What I can't do is writing data from PHP to SAP.

So maybe you can wrote an additional Unit-Test that demonstrates the usage of a "writing" function. Bases on that test I can start investigating the problem in a deeper way.

Thank you for your help

Raphael

**Comment by gkralik** [comment]
What exactly do you mean by "writing"? Can you show some code that you tried and that did not work?

**Comment by RaphaelHerd** [comment]
Hey,

thanks for the fast reply. I mean pass data from PHP to SAP and store them in SAP. The code example I used is listed below:

`  try {

     $conn = new SapConnection($config);

     $parms = array('USERNAME' => $account,
                    'PASSWORD' => array('BAPIPWD' => $passwd),
                    'LOGONDATA' => array('GLTGV' => '20161101', 'GLTGB' => '20161201'),
                    'ADDRESS' => array('FIRSTNAME' => 'xx', 'LASTNAME' => 'yyy'));

// get function handle of SAP function BAPI_USER_CHANGE (you can change user info here)
      $func = $conn->getFunction('BAPI_USER_CHANGE');

// invoke the BAPI_USER_CHANGE function based on the handle
// this invoke should "write" data to SAP
      $result = $func->invoke($parms);

// at this point of code my understanding is, that the call is synchonously executed and the data should be changed in SAP. But if we check SAP, the data is not modified at all. In addition we see in the tracing log of the SAP SDK, that the message that is send to SAP contains the fields we modified in the above part of the code.

      // close Connection
      $conn->close();
   }
   catch(SapException $ex) {

      echo 'Exception: ' . $ex->getMessage() . PHP_EOL.'<BR />';

      echo "**************** Connec failed ************************** <BR />";
   }
`

I ask this question because maybe we need to set some parameters, that your wrapper informs SAP to persist the data? I'm talking about some kind of transaction (e.g. database commit).

Based on that information it would be nice to have a unit-test that demonstrates that scenario.

Thanks for your help

**Comment by gkralik** [comment]
I did not try it myself, but from the top of my head I would say you migght need `BAPI_TRANSACTION_COMMIT` to commit your changes. Check the FM documentation of `BAPI_USER_CHANGE`

**Comment by gkralik** [comment]
https://archive.sap.com/discussions/thread/3272119

Have a look at the example given there.
