### ISSUE TITLE
Error while starting PHP with php_sapnwrfc

### ISSUE THREAD

**Issue by V3sp** [gkralik/php7-sapnwrfc#32]
Hi,

I'm affraid I cannot use your module. I installed Apache/2.4.25 (Win64) with PHP 7.0.15 x64 TS as a module on Windows Server 2012. 

There is no problem without  php_sapnwrfc and everything works smoothly. However when I add 
  extension=php_sapnwrfc.dll
to php.ini (as stated in README.md) and restart Apache I get an error:
  PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\\PrimeSoft\\php-7.0\\ext\\php_sapnwrfc.dll' - The specified module could not be found.\r\n in Unknown on line 0

The file php_sapnwrfc.dll exists. In fact it is "php_sapnwrfc-1.1.1-7.0-vc14-ts-x64.dll" renamed.

Are there any dependencies required? Visual C++ Redistributable for example? I think it already is installed (PHP works)...

Best wishes,
V3sp

**Comment by gkralik** [comment]
Have you tried using an absolute path to the module in your php.ini?

@ThaDafinser any other ideas?

**Comment by V3sp** [comment]
Same result when using absolute path.

**Comment by ThaDafinser** [comment]
@V3sp have you followed the guide here? https://github.com/gkralik/php7-sapnwrfc/blob/master/docs/installing_nwrfcsdk.md#windows

I think the SAP dependencies are missing, or your PATH is wrong for them.
