### ISSUE TITLE
Does the API support RFCTYPE_TABLE?

### ISSUE THREAD

**Issue by KlausSchade** [gkralik/php7-sapnwrfc#33]
Thanks for your work on a PHP / SAP Client.
The RFC which I try to invoke got back this RemoteFunction (using var_dump):
```php
object(SAPNWRFC\RemoteFunction)#2 (9) {
  ["name"]=>
  string(14) "RFC_READ_TABLE"
  ["DELIMITER"]=>
  array(5) {
    ["type"]=>
    string(12) "RFCTYPE_CHAR"
    ["direction"]=>
    string(10) "RFC_IMPORT"
    ["description"]=>
    string(47) "Zeichen für Markierung von Feldgrenzen in DATA"
    ["optional"]=>
    bool(true)
    ["defaultValue"]=>
    string(5) "SPACE"
  }
  ["OPTIONS"]=>
  array(5) {
    ["type"]=>
    string(13) "RFCTYPE_TABLE"
    ["direction"]=>
    string(10) "RFC_TABLES"
    ["description"]=>
    string(40) "Selektionsangaben, "WHERE-Klauseln" (in)"
    ["optional"]=>
    bool(false)
    ["defaultValue"]=>
    string(0) ""
  }
}
```
but I cant find a format for the OPTIONS parameter.  
When I use 
```php
$it = $rfc->getFunction('RFC_READ_TABLE');
$it->invoke([
        'DELIMITER' => '|',
        'OPTIONS' => [ 0 => "SNDLAD = '0400008118'" ]
]);
```
or
```php 
$it->invoke([
        'DELIMITER' => '|',
        'OPTIONS' => [ "SNDLAD = '0400008118'" ]
]);
```
or
```php 
$it->invoke(array(
        'DELIMITER' => '|',
        'OPTIONS' => array("SNDLAD = '0400008118'")
));
```
I got the error: "expected array for parameter OPTIONS "
This SAP RFC works fine with other client programs.
Thanks for your help.

**Comment by gkralik** [comment]
Hmm, I haven't tried, but according to http://stackoverflow.com/questions/24172130/how-where-to-specify-open-sql-in-pyrfc-call-to-sap-rfc-read-table (which is for python, but the overall interface is similar) this could work:

```php
$it->invoke(array(
        'DELIMITER' => '|',
        'OPTIONS' => [ ["TEXT" => "SNDLAD = '0400008118'"] ]
));
```

**Comment by gkralik** [comment]
In general, RFCTYPE_TABLE maps to PHP arrays.

**Comment by KlausSchade** [comment]
Thanks, this was a good hint.
It is the same with the FIELDS parameter. You have to know the KEY-names of the parameter array,
and that these parameters are arrays of arrays
```php
$result = $it->invoke([
        'QUERY_TABLE' => 'EDIDC',
        'ROWCOUNT' => 1,
        'DELIMITER' => '|',
        'OPTIONS' => [["TEXT" => "SNDLAD = '0400008118'"]],
        'FIELDS' => [["FIELDNAME" => "DOCNUM"]],
        'DATA' => $data
    ]);
```

**Comment by ThaDafinser** [comment]
Maybe we should add this to the readme/examples? @KlausSchade could you provide a full example?

**Comment by gkralik** [comment]
Yes, we definitely should improve the documentation and maybe add some information about type mapping.

**Comment by KlausSchade** [comment]
In the SAP System there is the default RFC_READ_TABLE. Here is an example to call this:
Please mention that there is one array for each FIELD !!!
```php
$rfcName = 'RFC_READ_TABLE';
$config = [
    'ashost' => 'xxx',
    'sysnr'  => '33',
    'client' => '222',
    'user' => 'X-USER',
    'passwd' => 'secret',
    'trace'  => SapConnection::TRACE_LEVEL_OFF,
];
$params = [
    'QUERY_TABLE' => 'CUSTOM_OR_SYS_TABLE',
    'ROWCOUNT' => 10,
    'DELIMITER' => '|',
    'OPTIONS' => [
        ["TEXT" => "DATUM = '2017-03-08' "]
    ],
    'FIELDS' => [
        ["FIELDNAME" => "MANDT"],
        ["FIELDNAME" => "UZEIT"],
        ["FIELDNAME" => "STATUS"],
        ["FIELDNAME" => "PROCESS"]
    ]
]; 

    $rfc = new SapConnection($config);
    $it = $rfc->getFunction($rfcName);
    $result = $it->invoke($params);
```
this works as 
```SQL
select MANDT, UZEIT, STATUS, PROCESS from CUSTOM_OR_SYS_TABLE where DATUM = '2017-03-08'
``` 
Now you can iterate over $result and get a string for each row, similar to that:
```
"222|035707|004|03"
```
I don't know if you can perform something like 
```SQL
select * from CUSTOM_OR_SYS_TABLE where DATUM = '2017-03-08'
``` 
Hopefully there is someone with deep SAP knowledge ;-)

**Comment by gkralik** [comment]
Have you tried an empty string for fields to fetch all fields (ie `'FIELDS' => ''`)?

**Comment by KlausSchade** [comment]
Oh yes, if you provide an empty array ``` 'FIELDS' => [] ``` you get all fields.
