### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by gkralik** [gkralik/php7-sapnwrfc#35]
General usage, parameter types, etc.

**Comment by hanni2001** [comment]
I would apreaciate an update on the documentation. I also would be glad to help.
I am a total newbe on this and having trouble to get started.

**Comment by gkralik** [comment]
I hope to have time later in the summer. In the meantime you can use the tests as a starting point. If that does not help you, feel free to open an issue.

**Comment by gkralik** [comment]
There is a work-in-progress of the new documentation at http://gkralik.github.io/php7-sapnwrfc.
Still incomplete though...

**Comment by gkralik** [comment]
Documentation is now available at http://gkralik.github.io/php7-sapnwrfc.
