### ISSUE TITLE
Reminder: Builds for windows

### ISSUE THREAD

**Issue by ThaDafinser** [gkralik/php7-sapnwrfc#36]
Just a reminder for me :+1:

**Comment by ThaDafinser** [comment]
Build are available here for `7.0` https://github.com/ThaDafinser/php7-sapnwrfc/pull/1

@gkralik could you already build your extension for `7.1` on unix?
I can't build it on windows currently.

**Comment by gkralik** [comment]
👍 
Yes, I built for 7.1, did not notice any problems. Do you get build errors?

**Comment by gkralik** [comment]
Just confirmed, builds fine for 7.0 and 7.1 under Linux.

**Comment by ThaDafinser** [comment]
I used the new guide + the new sdk-binary-tools (which worked nice for this php 7.0 build)
https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2

I would say no ...using php 7.1.3 (and the 7.1. deps ...)

Do you changed anything SAP related to build for 7.1?

# configure --disable-all --enable-cli --disable-zts --with-sapnwrfc=shared
[log1.txt](https://github.com/gkralik/php7-sapnwrfc/files/889398/log1.txt)

# nmake
[log2.txt](https://github.com/gkralik/php7-sapnwrfc/files/889399/log2.txt)

# nmake snap
[log3.txt](https://github.com/gkralik/php7-sapnwrfc/files/889400/log3.txt)

![image](https://cloud.githubusercontent.com/assets/533017/24601675/1d9306a2-185a-11e7-86f4-b2e39dd4d7bc.png)

**Comment by ThaDafinser** [comment]
BTW this warning also pops up in PHP 7.0
`WARNING: distro depends on sapnwrfc.dll, but could not find it on your system`

**Comment by gkralik** [comment]
Hmm, strange. I did not change anything. Seems we need to have a more detailed look at this issue...

**Comment by ThaDafinser** [comment]
building is fine :see_no_evil: : 
failed to properly configure PHP 7.1 in my local dev enviroment...(add sap .dll to php root)

added the build for 7.1 now to the PR / branch
https://github.com/ThaDafinser/php7-sapnwrfc/tree/build-1.1.2
https://github.com/ThaDafinser/php7-sapnwrfc/pull/1/files

**Comment by ThaDafinser** [comment]
Note: VC15 is a typo (it's VC14)

**Comment by gkralik** [comment]
Thanks, I have added them to the release page 👍
