### ISSUE TITLE
Provide sapnwrfc.dll 32-Bit

### ISSUE THREAD

**Issue by paymentplugins** [gkralik/php7-sapnwrfc#38]
Hello,

Thank you for maintaining this project. Is it possible to provide the sapnwrfc.dll for 32 bit? The SAP Marketplace downloads section does not appear to provide a 32 Bit version of the RFC SDK and MAMP on windows only supports 32 bit. This causes the warning message "%s1 is not a valid Win32 Application" as described in issue 37. 

It is proving prohibitively difficult to obtain this 32 bit dll file.

Kind Regards,

**Comment by paymentplugins** [comment]
It appears it would be a license violation if you were to publish that library. So I guess issue closed.

**Comment by gkralik** [comment]
You are right, we cannot provide the SAPNW RFC libraries.
