### ISSUE TITLE
Could not open the ICU common library

### ISSUE THREAD

**Issue by paymentplugins** [gkralik/php7-sapnwrfc#39]
Hi Guys,

I am getting an apache error that some required dlls can't be found.

Steps so far:

1. Unpacked and added nwrfcsdk from SAP Marketplace.
2. Added C:\nwrfcsdk\lib folder to Windows environment variables under PATH
3. Added php_sapnwrfc.dll extension to php.ini

Receiving the following message in apache error log.
`Could not open the ICU common library.
   The following files must be in the path described by
   the environment variable "PATH":
   icuuc34.dll, icudt34.dll, icuin34.dll`

The error is occurring when I attempt to connect as follows:
`use \SAPNWRFC\Connection as SapConnection;
$connection = new SapConnection($myprops);`

Any help is much appreciated.

**Comment by gkralik** [comment]
Are the required files in PATH?

**Comment by paymentplugins** [comment]
Yes, all the dll's are in the  C:\nwrfcsdk\lib folder and the include folder is there as well. In addition, echoing the %path% shows that the system variable is set.

Thanks,

**Comment by paymentplugins** [comment]
I downloaded the old 32 bit files from sourceforge and added them to the C:\nwrfcsdk folder and I am now able to connect. ¯\_(ツ)_/¯
