### ISSUE TITLE
Change license to MIT

### ISSUE THREAD

**Issue by gkralik** [gkralik/php7-sapnwrfc#4]
As this becomes more serious and stable now, I'd like to change the license of this project from [PHP-3.01](http://www.php.net/license/3_01.txt) to [Apache-2.0](http://www.apache.org/licenses/LICENSE-2.0).

The PHP license was only used because it was the default license for the skeleton extension, but I feel more comfortable with Apache-2.0.

As this concerns all contributors, I need your opinion on that, @ThaDafinser. If you're OK with the change, I'll create a PR for it.

The plan would be to have the license changed before the `0.6.0` release, which would be the first beta release now that everything is stable enough for serious testing.

**Comment by ThaDafinser** [comment]
I personally like more the `MIT`, because it's easy and let you do what you want, but Apache is also fine :+1: 

If you want a good overview:
http://choosealicense.com/licenses/

**Comment by gkralik** [comment]
`MIT` it is then. Have used it too and `Apache-2.0` doesn't offer any advantages here. I'll create a PR.
