### ISSUE TITLE
error executing functions in CentOS Linux release 7.3.1611 (Core) 64 bit

### ISSUE THREAD

**Issue by pingudinu** [gkralik/php7-sapnwrfc#40]
Sir I am facing error while executing functions on system using php 7.1 on CentOS Linux release 7.3.1611 (Core) 64 bit kernel  3.10.0-514.2.2.el7.x86_64 .

error: PHP Fatal error:  Uncaught Error: Call to undefined function sapnwrfc_rfcversion() in /usr/share/nginx/html/cr/a.php:11
Stack trace:
#0 {main}
  thrown in /usr/share/nginx/html/cr/a.php on line 11.

php info says : sapnwrfc

sapnwrfc support	enabled
 Version	1.0.0
SAP NW RFC SDK	7210.0.40

tried various versions 1.1/1.2 etc 

please help

**Comment by ThaDafinser** [comment]
you need to use 
```php
echo \SAPNWRFC\Connection::version();
echo \SAPNWRFC\Connection::rfcVersion();
```

**Comment by gkralik** [comment]
This extension does not provide a function `sapnwrfc_rfcversion()`. I suppose you mean `SAPNWRFC\Connection::rfcVersion()`?

**Comment by pingudinu** [comment]
Thanks ... you saved my Day.
