### ISSUE TITLE
Windows installation problem

### ISSUE THREAD

**Issue by szabizs** [gkralik/php7-sapnwrfc#42]
Hi guys,

I've done all steps, why do I get this error?

```
Warning: PHP Startup: Unable to load dynamic library 'c:/wamp64/bin/php/php7.0.10/ext/php_sapnwrfc.dll' - The specified module could not be found.
 in Unknown on line 0
PHP 7.0.10 (cli) (built: Aug 18 2016 09:48:53) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```

**Comment by szabizs** [comment]
Got it working after all, did not save the Path Variables, forgot to press Save and the dialog was still open.

**Comment by reachz** [comment]
dear, szabizs 

do you drop any file  php_sapnwrfc.dll on your path /php/ext/ 

i still got an error 
Warning: PHP Startup: Unable to load dynamic library 'D:\xampp\php\ext\php_sapnwrfc.dll' - The specified module could not be found.
 in Unknown on line 0

so do you mind if I beg your php_sapnwrfc.dll file from you.

**Comment by szabizs** [comment]
Hi @reachz ,
Sure, here it is, I use this:
PHP: 7.0.10
Compiler: MSVC14 (Visual C++ 2015)
Build date: Aug 18 2016 09:42:43
Architecture: x64




[php_sapnwrfc.zip](https://github.com/gkralik/php7-sapnwrfc/files/1684696/php_sapnwrfc.zip)

**Comment by reachz** [comment]
thank you, very much sir.
