### ISSUE TITLE
Error when building for PHP 7.2

### ISSUE THREAD

**Issue by aryapujianto** [gkralik/php7-sapnwrfc#43]
Sir, After I am `make install` and getting error 

`rm -f /usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c.ii /usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c.i && cc -E  -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/sap/nwrfcsdk/php7-sapnwrfc -DPHP_ATOM_INC -I/usr/sap/nwrfcsdk/php7-sapnwrfc/include -I/usr/sap/nwrfcsdk/php7-sapnwrfc/main -I/usr/sap/nwrfcsdk/php7-sapnwrfc -I/usr/include/php/20170718 -I/usr/include/php/20170718/main -I/usr/include/php/20170718/TSRM -I/usr/include/php/20170718/Zend -I/usr/include/php/20170718/ext -I/usr/include/php/20170718/ext/date/lib -I/usr/sap/nwrfcsdk/include  -DHAVE_CONFIG_H  -g -O2   -std=c99 -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DSAPonUNIX -DSAPwithUNICODE -D__NO_MATH_INLINES -DSAPwithTHREADS -DSAPonLIN -minline-all-stringops -fno-strict-aliasing -fno-omit-frame-pointer -fexceptions -funsigned-char -Wall -Wno-uninitialized -Wno-long-long -Wcast-align -pthread -fPIC  /usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c -o /usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c.ii && perl ./scripts/u16lit.pl -le /usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c.ii && /bin/bash /usr/sap/nwrfcsdk/php7-sapnwrfc/libtool --mode=compile cc  -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/sap/nwrfcsdk/php7-sapnwrfc -DPHP_ATOM_INC -I/usr/sap/nwrfcsdk/php7-sapnwrfc/include -I/usr/sap/nwrfcsdk/php7-sapnwrfc/main -I/usr/sap/nwrfcsdk/php7-sapnwrfc -I/usr/include/php/20170718 -I/usr/include/php/20170718/main -I/usr/include/php/20170718/TSRM -I/usr/include/php/20170718/Zend -I/usr/include/php/20170718/ext -I/usr/include/php/20170718/ext/date/lib -I/usr/sap/nwrfcsdk/include  -DHAVE_CONFIG_H  -g -O2   -std=c99 -DNDEBUG -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -DSAPonUNIX -DSAPwithUNICODE -D__NO_MATH_INLINES -DSAPwithTHREADS -DSAPonLIN -minline-all-stringops -fno-strict-aliasing -fno-omit-frame-pointer -fexceptions -funsigned-char -Wall -Wno-uninitialized -Wno-long-long -Wcast-align -pthread -fPIC -c /usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c.i -o sapnwrfc.lo
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:90:89: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO" passed 4 arguments, but takes just 3
 _ARG_WITH_RETURN_TYPE_INFO(arginfo_Connection_getAttributes, IS_ARRAY, NULL, 0)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:93:80: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO" passed 4 arguments, but takes just 3
 END_BEGIN_ARG_WITH_RETURN_TYPE_INFO(arginfo_Connection_ping, _IS_BOOL, NULL, 0)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:97:119: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX" passed 6 arguments, but takes just 5
 arginfo_Connection_getFunction, 0, 1, IS_OBJECT, "SAPNWRFC\\RemoteFunction", 0)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:101:81: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO" passed 4 arguments, but takes just 3
 ND_BEGIN_ARG_WITH_RETURN_TYPE_INFO(arginfo_Connection_close, _IS_BOOL, NULL, 0)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:104:95: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX" passed 6 arguments, but takes just 5
 ITH_RETURN_TYPE_INFO_EX(arginfo_Connection_setIniPath, 0, 1, _IS_BOOL, NULL, 0)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:108:89: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO" passed 4 arguments, but takes just 3
 _ARG_WITH_RETURN_TYPE_INFO(arginfo_Connection_reloadIniFile, _IS_BOOL, NULL, 0)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:111:96: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX" passed 6 arguments, but takes just 5
 TH_RETURN_TYPE_INFO_EX(arginfo_Connection_setTraceDir, 0, 1, _IS_BOOL, NULL, 1)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:115:98: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX" passed 6 arguments, but takes just 5
 _RETURN_TYPE_INFO_EX(arginfo_Connection_setTraceLevel, 0, 1, _IS_BOOL, NULL, 1)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:119:84: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO" passed 4 arguments, but takes just 3
 BEGIN_ARG_WITH_RETURN_TYPE_INFO(arginfo_Connection_version, IS_STRING, NULL, 0)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:122:87: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO" passed 4 arguments, but takes just 3
 IN_ARG_WITH_RETURN_TYPE_INFO(arginfo_Connection_rfcVersion, IS_STRING, NULL, 0)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:126:95: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX" passed 6 arguments, but takes just 5
 ITH_RETURN_TYPE_INFO_EX(arginfo_RemoteFunction_invoke, 0, 1, IS_ARRAY, NULL, 0)
                                                                               ^
/usr/sap/nwrfcsdk/php7-sapnwrfc/sapnwrfc.c:135:106: error: macro "ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX" passed 6 arguments, but takes just 5
 TYPE_INFO_EX(arginfo_RemoteFunction_isParameterActive, 0, 1, _IS_BOOL, NULL, 0)
                                                                               ^
Makefile:200: recipe for target 'sapnwrfc.lo' failed
make: *** [sapnwrfc.lo] Error `1``

I am using SAP NW RFC SDK 7.20, PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1

Please Help

**Comment by gkralik** [comment]
Are you sure you are using PHP 7.1.10? Looks more like 7.2 which is not yet supported by this extension.

**Comment by gkralik** [comment]
I will add support for PHP 7.2 in the next few days...

**Comment by aryapujianto** [comment]
oww sorry, Iam using php-fpm
I try 
`sudo phpize7.1`
`sudo ./configure --with-php-config=/usr/bin/php-config7.1 --with-sapnwrfc=/usr/sap/nwrfcsdk`
`sudo make`
and 
`sudo ln -sf /etc/php/7.1/mods-available/sapnwrfc.ini /etc/php/7.1/fpm/conf.d/20-sapnwrfc.ini`

and everything is fine, thanks for your response Sir ^_^

**Comment by gkralik** [comment]
PHP 7.2 support is in master.
