### ISSUE TITLE
Deactivate nested parameters

### ISSUE THREAD

**Issue by avadaneidanut** [gkralik/php7-sapnwrfc#45]
**Hi guys,**

I know we can disable parameters using: [activating-deactivating-parameters](https://gkralik.github.io/php7-sapnwrfc/usage.html#activating-deactivating-parameters)

Is there any possibility that we can disable table fields?

Example:
We have `TBL1` with the following structure:
```php
$tbl1 = [
    'FIELD1',
    'FIELD2',
    'FIELD3',
];
```
I want to retrieve only `FIELD1` and should call something like
```php
$function->setParameterActive('TBL1.FIELD2', false);
$function->setParameterActive('TBL1.FIELD3', false);
```

Is this possible in NWRFC SDK?

**Comment by gkralik** [comment]
This is currently not possible. I will have a look at it though...

**Comment by gkralik** [comment]
I'm not sure this is possible using the SAP NW RFC SDK.
