### ISSUE TITLE
Windows x86 build for PHP 7.1

### ISSUE THREAD

**Issue by chrisman42** [gkralik/php7-sapnwrfc#46]
Hi, can you help me out by building a php_sapnwrfc-1.1.2-7.1-vc14-ts-x86.dll? I need it for a PHP project and find only x64 or for PHP 7.0.

best regards,
Christian

**Comment by gkralik** [comment]
I do not use Windows myself...

@ThaDafinser can you help out?

**Comment by chrisman42** [comment]
Thanks for your quick response and for forwarding my request.

**Comment by ThaDafinser** [comment]
Sadly i am not having a working build enviroment anymore (I switched to the 🍎 )
Until i am having again such an enviroment, i cannot provid you with builds.

But its not that hard to do it on your own. I think with the description provided here you should be successfull: https://github.com/gkralik/php7-sapnwrfc/blob/master/docs/building.rst#building-on-windows

BTW @chrisman42 is there any reason why you need still x86?

**Comment by reachz** [comment]
dear, chisman42 

Are you solve this issues?

**Comment by chrisman42** [comment]
Hi, we switched to 64 bit and used the libraries compiled by ThaDafinser.

**Comment by reachz** [comment]
" switched to 64 bit " that mean you use XAMPP 64 Bit ?

so do you mind if I beg your php_sapnwrfc.dll file from you.

thank you, sir

**Comment by chrisman42** [comment]
no, not XAMPP. Apache, PHP, MySQL all installed and configured separately.
You can download the dll matching your architecture here: https://github.com/ThaDafinser/php7-sapnwrfc/tree/build-1.1.2

**Comment by reachz** [comment]
I see 
thank you, sir.
