### ISSUE TITLE
how to write data 

### ISSUE THREAD

**Issue by goalmaker** [gkralik/php7-sapnwrfc#48]
The code works fantastic to read data. 
Can you tell me how to write data to SAP?
using iis server, php7

**Comment by avadaneidanut** [comment]
Depends on the FMs you use. For BAPIs usually you need to call
BAPI_TRANSACTION_COMMIT after the main BAPI call. Can you give more details?

**Comment by goalmaker** [comment]
actually i am very new to this.
code details: [stack](https://stackoverflow.com/questions/48962760/sapnwrfc-connection-how-to-write-data-php)
My abap developer will provide me BAPI_TRANSACTION_COMMIT tomorrow.
i just want to know which function i have to use to send parameters to BAPI.

**Comment by avadaneidanut** [comment]
Same as calling a read function.

**Comment by goalmaker** [comment]
Hi
```
$INputParams = [
    'MATNR'=>'11010592.02',
    'WERKS'=>'1000',
    'KTEXT'=>'BON Black S 20',
    'LAEDA'=>'20170907',
    'MTART'=>'FERT',
    'MATKL'=>'01',
    'MEINS'=>'KAR',
    'EKGRP'=>'002',
    'DISMM'=>'PD',
    'BKLAS'=>'7920',
    'VPRSV'=>'S',
    'PREIS'=>220.52,
    'WAERS'=>'AED',
    'PEINH'=>1,
    'ERNAM'=>'SAP01'
  ];

$parms = [
       // 'I_MATTYPE' => 'FERT', 'I_PLANT' => '1000'
        "IT_MATERILALS" => ['defaultValue' => $INputParams]
        ];

$test = $result->invoke( $parms);

print_r($test);
```
////////

> Array
> (
>     [RETURN] =&gt; Array
>         (
>             [TYPE] =&gt; S
>             [ID] =&gt; ZMM                 
>             [NUMBER] =&gt; 100
>             [MESSAGE] =&gt; Successfully Updated                                                                                                                                                                                                        
>             [LOG_NO] =&gt;                     
>             [LOG_MSG_NO] =&gt; 000000
>             [MESSAGE_V1] =&gt;                                                   
>             [MESSAGE_V2] =&gt;                                                   
>             [MESSAGE_V3] =&gt;                                                   
>             [MESSAGE_V4] =&gt;                                                   
>             [PARAMETER] =&gt;                                 
>             [ROW] =&gt; 0
>             [FIELD] =&gt;                               
>             [SYSTEM] =&gt;           
>         )
> 
>     [IT_MATERILALS] =&gt; Array
>         (
>             [0] =&gt; Array
>                 (
>                     [MATNR] =&gt; 11010592.02       
>                     [WERKS] =&gt; 1000
>                     [KTEXT] =&gt; BON Black S 20                          
>                     [LAEDA] =&gt; 20170907
>                     [MTART] =&gt; FERT
>                     [MATKL] =&gt; 01       
>                     [MEINS] =&gt; KAR
>                     [EKGRP] =&gt; 002
>                     [DISMM] =&gt; PD
>                     [BKLAS] =&gt; 7920
>                     [VPRSV] =&gt; S
>                     [PREIS] =&gt; 220.52
>                     [WAERS] =&gt; AED  
>                     [PEINH] =&gt; 1
>                     [ERNAM] =&gt; SAP01       
>                 )
> 
>         )
> 
> )

**Comment by goalmaker** [comment]
@avadaneidanut  @gkralik 

Please help brothers. no proper tuts are available that my brain can analyse. As zero knowledge in SAP.

Git and Stack is the only place i can understand.

**Comment by goalmaker** [comment]
writing success. But only single data. How to write multiple rows with single invoke?

**Comment by gkralik** [comment]
That depends on the function module you are using/calling. Consult with your ABAP developer to find out.
Closing, as this is not an issue with the extension itself.

**Comment by avadaneidanut** [comment]
Sharw the success code.

On Feb 26, 2018 11:29, "Vivan Menezes" <notifications@github.com> wrote:

writing success. But only single data. How to write multiple rows with
single invoke?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/gkralik/php7-sapnwrfc/issues/48#issuecomment-368439741>,
or mute the thread

**Comment by goalmaker** [comment]
@gkralik  @avadaneidanut Thank you guys for your response.

I am able to send the data now. Learned to modify my code.

$parms = [
       // 'I_MATTYPE' => 'FERT', 'I_PLANT' => '1000'
        "IT_MATERILALS" => ['defaultValue' => $INputParams]
        ];
I modified the parms 
` $parms = [
      
        "IT_MATERILALS" => ['0' => $INputParams,'1' => $INputParams2]
    
        ];`

and now it worked without any issue. 
One thing is that now I am not getting any success message in RETURN but I get processed data.
