### ISSUE TITLE
Change invoke rtrim to false as default

### ISSUE THREAD

**Issue by avadaneidanut** [gkralik/php7-sapnwrfc#49]
I think we should change rtrim option to false by default. It breaks compatibility with older versions and I think it will affect many users. It already affects all my applications.

**Comment by gkralik** [comment]
Yes, you are right. I will push an updated version soon.

**Comment by gkralik** [comment]
Version 1.2.1 makes the `rtrim` option default to `false`.
Documentation has been updated to reflect this change.
