### ISSUE TITLE
Does anyone have a precompiled Windows dll for PHP 7.2.4 ?

### ISSUE THREAD

**Issue by szabizs** [gkralik/php7-sapnwrfc#50]
Hi guys,

Does someone have a precompiled DLL for this version?

**Version: PHP Version 7.2.4**
„
Windows NT M900327 10.0 build 16299 (Windows 10) AMD64
„

Thanks in advance!

**Comment by szabizs** [comment]
Thank you @avadaneidanut  (Mersi!)

![image](https://user-images.githubusercontent.com/5064872/38545883-c8856f68-3cb3-11e8-9941-c8715fd9c0dd.png)

**Comment by lubberscorrado** [comment]
Could  you provide the nts version aswell?
