### ISSUE TITLE
PHP Extensions.

### ISSUE THREAD

**Issue by iespino00** [gkralik/php7-sapnwrfc#51]
Hello, thanks for this repository, but my php doesn't detect the extension .dll . Can i help me?

**Comment by gkralik** [comment]
Do you have more details?

**Comment by ignaciomdominguez** [comment]
Hi,
same issue.

PHP Warning:  PHP Startup: Unable to load dynamic library 'php_sapnwrfc' (tried: ext\php_sapnwrfc (No se puede encontrar el m¾dulo especificado.), ext\php_php_sapnwrfc.dll (No se puede encontrar el m¾dulo especificado.)) in Unknown on line 0
PHP 7.2.5 (cli) (built: Apr 25 2018 02:19:27) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

PHP.ini has extension_dir = "ext"
I'm using PHP 7.2.5, VC15, SAPNWRFC SDK 750. I'm trying to run in IIS (NTS) WINx64

Compilation was successfull (no warnings nor errors)
Preprocessor definitions: /PHP_WIN32 /ZEND_WIN32 /ZEND_DEBUG=0 /COMPILE_DL_SAPNWRFC
/_UNICODE /UNICODE /SAPwithUNICODE /_CRT_SECURE_NO_WARNINGS /ZTS=0

Any idea?
I appreciate any help
Thanks!

**Comment by avadaneidanut** [comment]
Try to add the sdk lib folder to path.

**Comment by ignaciomdominguez** [comment]
It was already added. Thks

**Comment by gkralik** [comment]
Is this solved?

**Comment by ignaciomdominguez** [comment]
No. PHP still unrecognize .dll as an extension

**Comment by iespino00** [comment]
I can not either, I have SAP ERP 2005 29 (06/2017) sap.com SAP ERP 6.0

**Comment by ignaciomdominguez** [comment]
Now it's working !!!!
librfc32.dll were in c:\windows\syswow64 and c:\windows\system32. Even if both are in PATH variable php doesn't search in this places. I moved the file librfc32.dll to \ext directory.
In the other hand I remove ZTS=0 from preprocesor directives.
Now is working.
Thanks
