### ISSUE TITLE
I feel stupid but ....

### ISSUE THREAD

**Issue by kf202020** [gkralik/php7-sapnwrfc#53]
....I cannot install the whole thing :|
Followed the installation guide. Zero error but "php -m | more" still doesn't display the line sapnwr.

Tried even with different builds .... actually trying with Php 7.2.5-1+ubuntu17.10.1+deb.sury.org+1

Any idea? 

Thx

**Comment by gkralik** [comment]
Have you enabled the extension in your `php.ini`?

**Comment by kf202020** [comment]
I cannot find any "enable extension" I just copied the extension=sapnwrfc.so without semicolumns following the guide .....
I put this under ;dynamic extensions

**Comment by gkralik** [comment]
That should suffice. Any error output when you launch a script?

**Comment by gkralik** [comment]
Did you put the extension line in the correct php.ini file? Debian uses separate files for CLI and web IIRC.

**Comment by kf202020** [comment]
```
<?php
$parameters = [
    'ashost' => 'my.sap.system.local',
    'sysnr'  => '00',
    'client' => '123',
    'user' => 'DEMO',
    'passwd' => 'XXXX',
];

// connect
$connection = new SAPNWRFC\Connection($parameters);

// do work here

// close the connection
$connection->close();
?>

```


Tried this one .... nothing happened.
I used phpinfo to get php.ini path .... is that correct ?

**Comment by gkralik** [comment]
It depends on whether you are using the script from CLI or web. If you put the extension line in a php.ini file and it doesn't show up with `php -m` and does not print warnings about being unable to load the extension, it most likely is the wrong file.

You can try `php -dextension=sapnwrfc.so -m` from CLI to check if the extension loads.

**Comment by kf202020** [comment]
![image](https://user-images.githubusercontent.com/39485079/40304716-0edffa32-5cf8-11e8-9d66-7f138ca41e2d.png)

Now I Got something like this ..... Really didn't know about the cli/web .....
