### ISSUE TITLE
Any way to turn off the trace file?

### ISSUE THREAD

**Issue by lhenkel** [gkralik/php7-sapnwrfc#54]
I call this library from multiple directories and it puts dev_rfc.trc wherever I call it.

It creates when I put this in startup parameters:
$parameters = [
'trace' => \SAPNWRFC\Connection::TRACE_LEVEL_OFF,
..
];
Or when I do this 
SAPNWRFC\Connection::setTraceLevel(0);
It creates a file telling me I turned the trace level down.

When I copy the sapnwrfc.ini to my current directory and change RFC_TRACE_DIR=/tmp it works correctly, but I can't copy that everywhere I call it.

The sapnwrfc.ini says "By default the NW RFC library looks for the sapnwrfc.ini file    
 in the current working directory of the process. If you want     
 to change that behaviour, you can set an alternative directory   
  using the API RfcSetIniPath()
But I don't know how to do that.  I tried calling that from the library, but it didn't seem to do anything.

This is driving me nuts, I'd appreciate any help.

**Comment by gkralik** [comment]
https://gkralik.github.io/php7-sapnwrfc/usage.html#trace-levels

**Comment by gkralik** [comment]
As far as I'm aware, you cannot fully suppress the generation of the trace file. Your best option is turning down the trace level and setting a different trace directory by using `SAPNWRFC\Connection::setTraceDir($path)` or by using the `RFC_TRACE_DIR` environment variable.
