### ISSUE TITLE
Will this work on Ubuntu?

### ISSUE THREAD

**Issue by rohit1290** [gkralik/php7-sapnwrfc#55]
I followed the instruction available at https://gkralik.github.io/php7-sapnwrfc/installation.html#installing-nwrfcsdk and for the step "Installing the SAP NW RFC library" I was not able to find any lib for Ubuntu on SAP official site.

Can you please help me with this.

**Comment by gkralik** [comment]
You need access to the SAP customer portal in order to download the SDK. It is not publicly available AFAIK.

**Comment by rohit1290** [comment]
Yes, I did that. I only found SDK for the following:

- AIX 64BIT
- HP-UX ON IA64 64BIT
- HP-UX ON PA-RISC 64BIT
- LINUX ON IA32 32BIT
- LINUX ON IA64 64BIT
- LINUX ON POWER BE 64BIT
- LINUX ON POWER LE 64BIT
- LINUX ON X86_64 64BIT
- LINUX ON ZSERIES 64BIT
- OS/400
- SOLARIS ON SPARC 64BIT
- SOLARIS ON X86_64 64BIT
- WINDOWS SERVER ON IA32 32BIT
- WINDOWS ON IA64 64BIT
- WINDOWS ON X64 64BIT
- Z/OS 64BIT

**But there was no RFC SDK for Ubuntu**

**Comment by gkralik** [comment]
Ubuntu is Linux-based, so use IA32 or x86_64, depending on your platform.
