### ISSUE TITLE
error in make 

### ISSUE THREAD

**Issue by sarakimart** [gkralik/php7-sapnwrfc#56]
Hi
I have problem in make .so in linux 

`/app/hrportal/sap/php7-sapnwrfc/sapnwrfc.c:532:67: error: macro "zend_hash_add" requires 6 arguments, but only 3 given
/app/hrportal/sap/php7-sapnwrfc/sapnwrfc.c:649:32: error: macro "RETVAL_STRINGL" requires 3 arguments, but only 2 given
/app/hrportal/sap/php7-sapnwrfc/sapnwrfc.c:665:32: error: macro "RETVAL_STRINGL" requires 3 arguments, but only 2 given
/app/hrportal/sap/php7-sapnwrf1/sapnwrfc.c:871:68: error: macro "zend_hash_update" requires 6 arguments, but only 3 given`

**Comment by gkralik** [comment]
Which PHP version are you trying to build for?

**Comment by sarakimart** [comment]
php 7.0.2 

but my php 7.0.2 was instaleed in  /app/hrportal/opt/php-7.0.27/bin/php   and  /usr/include/php  is phph 5

**Comment by gkralik** [comment]
Make sure you use PHP 7 includes when building. Something like the following:

```
make distclean
/app/hrportal/opt/php-7.0.27/bin/phpize
./configure --with-sapnrfc=/path/to/nwrfcsdk --with-php-config=/app/hrportal/opt/php-7.0.27/bin/php-config
make
