### ISSUE TITLE
windows dlls for php 7.2

### ISSUE THREAD

**Issue by lubberscorrado** [gkralik/php7-sapnwrfc#58]
Could you please provide precompiled windows dlls for the latest releases as you did until march 2017? :)
Especially to have working nts dlls for PHP 7.2. Thank you!

**Comment by gkralik** [comment]
As I do not have access to a Windows machine, I cannot help you with that. If someone wants to provide builds, I'm happy to upload them, otherwise just follow the build instruction and build it yourself.

**Comment by sandrociceros** [comment]
[php_sapnwrfc.zip](https://github.com/gkralik/php7-sapnwrfc/files/2295892/php_sapnwrfc.zip)
