### ISSUE TITLE
SAP NW RFC SDK 7.50

### ISSUE THREAD

**Issue by renanwilliam** [gkralik/php7-sapnwrfc#59]
This package works with SAP NW RFC SDK 7.50?

**Comment by gkralik** [comment]
It compiles without problems and there are no failed tests, so it should work. If you find any problems, please report them.

**Comment by MarcioRM78** [comment]
Yes! I'm using without any problem.
Thanks a lot for this wonderful and "KISS principle" solution Mr. Kralik =)

**Comment by renanwilliam** [comment]
yes, it's worked here also! Thank you!
