### ISSUE TITLE
Windows shutdown error

### ISSUE THREAD

**Issue by ThaDafinser** [gkralik/php7-sapnwrfc#6]
Now i get this error on shutdown.

Calling RFC functions before works fine.

This error also comes with the simple command `php -m`

![image](https://cloud.githubusercontent.com/assets/533017/13072147/e6609ac0-d497-11e5-8f3c-717cd2cc010e.png)

**Comment by gkralik** [comment]
Which version did you use?

Can you tell what was the last version where you did not experience this
error?

**Comment by ThaDafinser** [comment]
Latest. Need to go through the commits, will inform you when i found the last working commit.

**Comment by ThaDafinser** [comment]
Needed to build a lot of times to get the commit :+1: 

With this commit `fd56ff26c12ef099e4c6a21aa39494432cba58af` it stopped to work

https://github.com/gkralik/php7-sapnwrfc/commit/fd56ff26c12ef099e4c6a21aa39494432cba58af

```
;extension=php_sapnwrfc-c4ecab0276d2e8159e8138680c8571a3b50da935.dll	; nope
;extension=php_sapnwrfc-20f4f437a2d0f5fd7074afbcf5df883882bc18ff.dll	; WORK
;extension=php_sapnwrfc-afd90b6e667f89ad586caa193bda842c914aca98.dll	; nope
;extension=php_sapnwrfc-58251b123861eddf76406120a8a909dc7c20e19c.dll	; nope		
;extension=php_sapnwrfc-8d1f9276b84842ec7d53ece3fd1d0e75c12d2d8c.dll	; WORK
;extension=php_sapnwrfc-88b3ba2319a94417f2cbf6184de427c1aa6a6a5d.dll	; WORK
 extension=php_sapnwrfc-fd56ff26c12ef099e4c6a21aa39494432cba58af.dll  ; nope
```

**Comment by gkralik** [comment]
Ok, thanks. I'll have a look in the evening.. seems strange. Can you
show me a stripped down version of the PHP script you use that I can use
to try to reproduce the issue?

**Comment by gkralik** [comment]
@ThaDafinser can you try the `fix-shutdown-error-on-windows` branch and
check if it makes a difference? Just a wild guess, but maybe it helps me
narrow down the problem...

**Comment by ThaDafinser** [comment]
@gkralik that branch works.

Compiler shows me two warnings now
![image](https://cloud.githubusercontent.com/assets/533017/13075912/e90404ee-d4ae-11e5-8e17-a2281a935c9d.png)

**Comment by gkralik** [comment]
Very well. The please update the fixed branch and try again... I changed
the handling of the errorInfo member. Curious if that works now.

**Comment by ThaDafinser** [comment]
@gkralik still work with the 2nd commit in that branch.
Two warnings still exist

**Comment by gkralik** [comment]
OK, I'll fix the unused error_info error, but the signed/unsigned
mismatch should already have been resolved in master...

**Comment by gkralik** [comment]
Merged and fixed on current master. Thanks for your help.
