### ISSUE TITLE
Windows builds for PHP 7.2.*

### ISSUE THREAD

**Issue by avadaneidanut** [gkralik/php7-sapnwrfc#62]
@gkralik Attached you can find the windows builds for latest extension version. I kindly ask you to include them in the latest release. I've tested all of them.
[php_sapnwrfc 7.2.zip](https://github.com/gkralik/php7-sapnwrfc/files/2375334/php_sapnwrfc.7.2.zip)

PHP Version used for compiling is 7.2.9 VC 15.

**Comment by gkralik** [comment]
Thanks for providing these. Can you give me a quick summary of the differences of these and the already provided builds at https://github.com/gkralik/php7-sapnwrfc/releases/tag/1.2.1?

**Comment by gkralik** [comment]
Ahh, I didn't see this. Thanks a lot, I will add the x86 builds :+1:
