### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by Zavy86** [gkralik/php7-sapnwrfc#63]
hi, I followed the instructions on the page https://gkralik.github.io/php7-sapnwrfc/installation.html

Downloaded NWRFC_51-20004565.SAR for Linux on X86_64 (my release id Debian 9)

Extracted with SAPCAR

Moved the nwrfcsdk into /usr/sap/nwrfcsdk

Created the file /etc/ld.so.conf.d/nwrfcsdk.conf with contents /usr/sap/nwrfcsdk/lib and run ldconfig.

but in the directory /usr/sap/nwrfcsdk/lib is not present sapnwrfc.so file but libsapnwrfc.so

addedd to php.ini extension=sapnwrfc.so

reloaded apache2 

but the extension does not load

tried also with extension=libsapnwrfc.so into php.ini but it doesen't work too..

can you help me please?

**Comment by gkralik** [comment]
I just noticed the documentation is a little unclear here: after downloading the SAP NW RFC SDK and setting up ld(1) paths, you need to build the PHP extension (see [Building from source](https://gkralik.github.io/php7-sapnwrfc/building.html). You cannot directly load `libsapnwrfc.so` as it is no PHP extension.

**Comment by Zavy86** [comment]
Aaaaahhh, ok it work now! thank you

**Comment by ayashanoor** [comment]
Hi Zavy86 
Please share the full process about PHP and SAP connectivity.

**Comment by Zavy86** [comment]
Hi, I try this https://gkralik.github.io/php7-sapnwrfc/building.html
