### ISSUE TITLE
Port configuration

### ISSUE THREAD

**Issue by MarcioRM78** [gkralik/php7-sapnwrfc#64]
Hi

Is there a way to configure the port connection on host?

Like...

$parameters = [
'ashost' => 'sap.company.net',
**'port' => '3302',**
'sysnr'  => '01',
'client' => '500',
'user' => 'XXXXXXXX',
'passwd' => 'XXXXXXXX'
];

I couldn't found something about it on documentation.
Default port is 3301 (as my colleague from SAP team told me), right?

Thank you in advance.

**Comment by gkralik** [comment]
I am not aware of a `port` setting in the NW RFC.
IIRC the port number used by the connection is `33+sysnr`.

**Comment by MarcioRM78** [comment]
Hi, you are absolutely correct, I changed the sysnr to 02 and it worked.
My lack of knowledge in how SAP. 
Thanks for your quickly response and congratulations for your job, it's really useful.
