### ISSUE TITLE
upper/lower case flag

### ISSUE THREAD

**Issue by Zavy86** [gkralik/php7-sapnwrfc#65]
hi, how can I indicate that I want to run the remote function with the case insensitive flag enabled?

![image](https://user-images.githubusercontent.com/2051811/51732661-3c881f00-207f-11e9-8821-0532d84da3bd.png)

**Comment by gkralik** [comment]
I am not aware of such a setting in SAP NW RFC SDK. Isn't that something special to SE37 and related transactions?
