### ISSUE TITLE
Building for Mac OS

### ISSUE THREAD

**Issue by bigreja** [gkralik/php7-sapnwrfc#66]
There is currently a version of SAP NW RFC SDK for Mac OS, i tried building this extension on my mac, but there are many errors, i have replaced on configure script the names the libraries suitable for Mac OS.
but executing Make i got this error:

/usr/local/sap/nwrfcsdk/include/sapucx.h:303:14: fatal error: 'uchar.h' file not found

i'm not familiar with building environments.
any help please?

**Comment by gkralik** [comment]
I do not use macOS, so I cannot help you there.
