### ISSUE TITLE
Crash Running under php-fpm

### ISSUE THREAD

**Issue by bigreja** [gkralik/php7-sapnwrfc#67]
Tested on ubuntu 18.04
It runs ok using command line php script.php
but when running on apache2 and PHP through php-fpm it crashes php-fpm
error form log is simply
[Wed Jan 30 17:14:55.591207 2019] [proxy_fcgi:error] [pid 2513] AH01067: Failed to read FastCGI header
[Wed Jan 30 17:14:55.591262 2019] [proxy_fcgi:error] [pid 2513] (104)Connection reset by peer: AH01075: Error dispatching request to : 

On debug log from php-fpm:

[30-Jan-2019 17:26:48.596667] DEBUG: pid 3146, fpm_got_signal(), line 76: received SIGCHLD
[30-Jan-2019 17:26:48.597022] WARNING: pid 3146, fpm_children_bury(), line 253: [pool web1] child 3206 exited with code 255 after 28.730796 seconds from start

**Comment by gkralik** [comment]
Without providing a test script to reproduce the crash(?) and more information, I will not be able to investigate.

**Comment by bigreja** [comment]
I have an Ubuntu 18.04 server installation with ISPConfig installed, 
i've used a sample from your documentation.

<?php
use SAPNWRFC\Connection as SapConnection;
use SAPNWRFC\Exception as SapException;

$config = [
    'ashost' => '192.168.0.163',
    'sysnr'  => '00',
    'sysid'  => 'PRD',
    'client' => '100',
    'user'   => 'WAVE-RFC',
    'passwd' => 'mebra2013',
    'trace'  => SapConnection::TRACE_LEVEL_OFF,
];

try {
    $c = new SapConnection($config);

    $f = $c->getFunction('STFC_CHANGING');
    $result = $f->invoke([
        'START_VALUE' => 0,
        'COUNTER' => 1,
    ]);
        print_r($result);

} catch(SapException $ex) {
    echo 'Exception: ' . $ex->getMessage() . PHP_EOL;
}
?>


it works running from command line, php file.php
result is:

Array
(
    [COUNTER] => 2
    [RESULT] => 1
)

but when running from a browser it crashes giving 503 error, ISPConfig allows me to run PHP as fastCGI, PHP-FPM, on fast CGI i get an error when loading extension.
PHP FPM crashes when running script
I'm using Apache2 web server.

**Comment by luckyduck** [comment]
I can confirm this behaviour. Also see #68 for more information

**Comment by gkralik** [comment]
Any chance to get a coredump of the crash?

**Comment by gkralik** [comment]
Also, I'm missing the PHP version you are using!?

**Comment by bigreja** [comment]
php -v result:
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

I will try to get a core dump

**Comment by gkralik** [comment]
@bigreja any update on this?

**Comment by gkralik** [comment]
Closing as there has been no response for a month now.
