### ISSUE TITLE
R3Name/SID can not be defined

### ISSUE THREAD

**Issue by reeperbahnause** [gkralik/php7-sapnwrfc#71]
Hi,   
I could not find a way to define the  `R3NAME`/ `SID` / `SYSID` or whatever the correct name would be.
At least it's not in the stub so I dont know if this value could still be set?
Could you help me with this?

Thank you for the nice work!

**Comment by gkralik** [comment]
The supported connection settings are linked from the documentation: [Connecting to a SAP system](https://gkralik.github.io/php7-sapnwrfc/usage.html#connecting-to-a-sap-system)
