### ISSUE TITLE
Problem loading php extension.

### ISSUE THREAD

**Issue by luisalonso97** [gkralik/php7-sapnwrfc#76]
Hi, we have a problem loading the latest build (1.2.1 - 2018-03-08) under Windows Server 2016 64-bit.
We have PHP 7.2.11 running on IIS. I have followed the steps to set up the SAP NW RFC library under "C:\nwrfcsdk", it's already included in Path.
But trying on load the lastest nts-64bit build php doesn't find the dll.
It outputs the message 
"Message: PHP Startup: Unable to load dynamic library 'sapnwrfc' (tried: C:\php\ext\sapnwrfc (The specified procedure could not be found.), C:\php\ext\php_sapnwrfc.dll (The specified module could not be found.))"
Are there any problems with my setup?
Here's a tree view of my nwrfcsdk folder 
![image](https://user-images.githubusercontent.com/15828168/57150442-ef110180-6d93-11e9-86e4-5ed00c52656a.png)
And the sapnwrfc.dll it's the nts-64bit latest build which is also in php/ext.
I have already tried changing the extension path to be absolute.
Thank You in Advance.

**Comment by h-mulahmetovic** [comment]
Hi,

I have the same problem.
I'm using the prebuilt php_sapnwrfc-1.2.1-7.2.8-vc15-nts-x64.dll.

Running Windows Server 2016 x64 with PHP 7.2.8 nts x64
![image](https://user-images.githubusercontent.com/31687390/59013434-3cbcd600-883a-11e9-9321-d4a6d58fca04.png)



nwrfcsdk located in C:\. 
![image](https://user-images.githubusercontent.com/31687390/59013473-552cf080-883a-11e9-89de-3a14a2113374.png)



System Environment Variable is set.
![image](https://user-images.githubusercontent.com/31687390/59013358-0a12dd80-883a-11e9-8dd6-6df6e4ac6407.png)



php_sapnwrfc.dll is located under C:\PHP\ext\
![image](https://user-images.githubusercontent.com/31687390/59013543-7261bf00-883a-11e9-90c0-f094ce4c8b8f.png)



Referenced in .ini
![image](https://user-images.githubusercontent.com/31687390/59013560-83123500-883a-11e9-997e-21a71416d0ea.png)



Error Log:
[06-Jun-2019 06:54:37 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'php_sapnwrfc.dll' (tried: ext\php_sapnwrfc.dll (The specified module could not be found.), ext\php_php_sapnwrfc.dll.dll (The specified module could not be found.)) in Unknown on line 0


Any idea what I'm doing wrong?

Thank You in advance.

**Comment by gkralik** [comment]
Any updates?
