### ISSUE TITLE
v1.3 bild extension

### ISSUE THREAD

**Issue by stuli3** [gkralik/php7-sapnwrfc#77]
Please make a build to PHP7.3 nts x64 windows dll
Thanks!

**Comment by gkralik** [comment]
Sorry, I do not have access to a Windows box. Building yourself should not be hard.

**Comment by stuli3** [comment]
Sorry, but it is... Someone else who do it to version 1.2.1?

**Comment by avadaneidanut** [comment]
@gkralik Attached you can find the builds for Windows PHP version 7.3.8 and library version 1.3.0. You can include them in the release if you want. cc @stuli3 



[php_sapnwrfc-1.3.0-7.3.8-vc-15.zip](https://github.com/gkralik/php7-sapnwrfc/files/3526577/php_sapnwrfc-1.3.0-7.3.8-vc-15.zip)

**Comment by gkralik** [comment]
@avadaneidanut thanks, I'll add them in the next few days.

**Comment by gkralik** [comment]
https://github.com/gkralik/php7-sapnwrfc/releases/tag/1.3.0
