### ISSUE TITLE
Retrieve all informations about an RFC or a BAPI

### ISSUE THREAD

**Issue by mdemori** [gkralik/php7-sapnwrfc#79]
Hello, 

I'm migrating from saprfc (https://sourceforge.net/projects/saprfc/files/saprfc/1.4.1/) to sapnwrfc, and now i need something that seem missing from sapnwrfc lib.

Sometime I need a way to get all details about an rfc/bapi so i can have all available field, type and information about the function.

On the old library there is a function called saprfc_function_interface that return all information about the given function, all fields with all parameters, type and so on..
This is an example of what information I can retrieve:

```
$def = array (
  array (
    "name"=>"PARAMETER",      // name of import, export parameter or internal table
    "type"=>"IMPORT",         // type: IMPORT, EXPORT, TABLE
    "optional"=>0             // 1 - optional parameter
    "def"=> typedef           // type definition (elementary SAP data type or structure)
  ),
  
  ............

)
  typedef = array (
    array ("name"=>"item1" "abap"=>"C", "len"=>30, "dec"=>0),
    array ("name"=>"item2" "abap"=>"I", "len"=>4, "dec"=>0),
    .....
  )
```

This is really usefull because I don't need to ask for support when i need to use a new function that will be enabled for my requirements.

There is a way to replicate this function? I just try to use the getFunction() method but seem that this method miss lot of information... as example I've have a call to an RFC that require a structure like this:

```
['INFO'] => [ 
                      ['INFO_ID'],
                      ['OTHER_INFO01'],
                      ['OTHER_INFO02'],
                      ['OTHER_INFO03'],
];

When i use the getFunction() I get only below information:

[INFO] => [        
            [type] => RFCTYPE_TABLE
            [direction] => RFC_TABLES
            [description] => 
            [optional] => 1
            [defaultValue] => 
        ]
 ```

there is a way to obtain all missing information?

**Comment by gkralik** [comment]
I will have a look at this.

**Comment by gkralik** [comment]
At the moment, there is no way to get additional type information. I have it on my list, but cannot give you an ETA on this.

**Comment by mdemori** [comment]
Thank for you hard work! I really appreciate this! thank you

**Comment by gregor-j** [comment]
Hello,

my project relies on the data types declared by SAP for automatic type conversion. In comparison to [Eduard Kouckys legacy saprfc PHP module](http://saprfc.sourceforge.net/), yours (and [P. Hardings](https://github.com/piersharding/php-sapnwrfc)) module is missing `name` and `type` of the member elements of structs and tables. Therefore I cannot automagically convert SAP DATE and TIME elements into PHP DateTime objects whenever these are in a table or struct.

It would be a great help for my project if your module could return the members of tables and structs.

**Comment by gkralik** [comment]
I'll have a look at it in the coming days and will get back to you.

**Comment by mdemori** [comment]
Thank you very much!!!!

**Comment by gkralik** [comment]
I have started working on this. No ETA yet though...

**Comment by avadaneidanut** [comment]
@gkralik the python official package has this kind of functionality.

**Comment by gkralik** [comment]
Interesting, looks much like what I did.

I'm thinking about a `RemoteFunction::getParameterDescription($fieldName = null)` or `RemoteFunction::getFunctionDescription()`. It does already work, but lacks tests.
Hopefully, this will land in the next 2-3 weeks in master.

**Comment by gkralik** [comment]
The current master now contains a method `getFunctionDescription` for a `RemoteFunction` that provides access to the function's interface description.

Example return value for the `STFC_STRUCTURE` function:
```php
array (
  'ECHOSTRUCT' => 
  array (
    'name' => 'ECHOSTRUCT',
    'type' => 'RFCTYPE_STRUCTURE',
    'direction' => 'RFC_EXPORT',
    'description' => 'Exporting structure',
    'ucLength' => 264,
    'nucLength' => 144,
    'decimals' => 0,
    'optional' => false,
    'default' => '',
    'typedef' => 
    array (
      'RFCFLOAT' => 
      array (
        'name' => 'RFCFLOAT',
        'type' => 'RFCTYPE_FLOAT',
        'ucLength' => 8,
        'ucOffset' => 0,
        'nucLength' => 8,
        'nucOffset' => 0,
        'decimals' => 16,
      ),
      /* ... */
    ),
  ),
  'RESPTEXT' => 
  array (
    'name' => 'RESPTEXT',
    'type' => 'RFCTYPE_CHAR',
    'direction' => 'RFC_EXPORT',
    'description' => 'Exporting response message',
    'ucLength' => 510,
    'nucLength' => 255,
    'decimals' => 0,
    'optional' => false,
    'default' => '',
  ),
  'IMPORTSTRUCT' => /* ... */,
  'RFCTABLE' => /* ... */
)
```

Note: this is still a work in progress, documentation is not finished yet and the method and/or field names could change. Feedback welcome.

**Comment by mdemori** [comment]
Thank you! I will try immediately tomorrow morning! currently I don't have access to our test system I will back to you as soon as I did some tests

**Comment by gregor-j** [comment]
I tested the current `master` branch, and `getFunctionDescription()` works as promised.

Thank you! :smiley:
