### ISSUE TITLE
need help on using sapnwrfc

### ISSUE THREAD

**Issue by patrickpdx** [gkralik/php7-sapnwrfc#82]
Hi there,

I am trying to use sapnwrfc to connect to SAP system, here is my case (Windows server 2016, apache 2.4.35/PHP 7.2.10):

I have downloaded the "php_sapnwrfc_x86.dll" file, and put to the PHP extension folder, and enabled this extension without problem.

now I am trying to write the code based on the example on this site.

	$sap = new SAPNWRFC\Connection(array(
						"logindata"=>array(
							"ASHOST"=>"xxx"		// application server
							,"SYSNR"=>"xx"		// system number
							,"CLIENT"=>"xxx"		// client
							,"USER"=>"xxxxx"		// user
							,"PASSWD"=>"xxxxx"	// password
							)
						,"show_errors"=>false		// let class printout errors
						,"debug"=>false)) ; 			// detailed debugging information

when running, I got the following error:

**Fatal error: Uncaught Error: Class 'SAPNWRFC\Connection' not found--**

I don't know and not intend to build from the source for this sapnwrfc, so any file I need to get and from where?

and I have used the "php_saprfc_528.dll" in the environment Apache 2.2.8/PHP 5.2.5 to connect to SAP, I got some sample code online, the following code worked fine with a file (saprfc.php) which define saprfc class:

$sap = new saprfc(array(
		"logindata"=>array(
		"ASHOST"=>"xxx"		// application server
		,"SYSNR"=>"xx"		// system number
		,"CLIENT"=>"xxx"		// client
		,"USER"=>"xxxxx"		// user
		,"PASSWD"=>"xxxxx"	// password
		)
	,"show_errors"=>false		// let class printout errors
	,"debug"=>false)) ; 			// detailed debugging information

where I can get this similar file for sapnwrfc?

regards,
Patrick

**Comment by gkralik** [comment]
https://gkralik.github.io/php7-sapnwrfc/installation.html
https://gkralik.github.io/php7-sapnwrfc/introduction.html#quick-start

**Comment by patrickpdx** [comment]
Hi Gregor,

Thanks for the information, but I am not able to "Download the SAP NW RFC library", I have no account on the SAP ONE Support launchpad. what I should do? how do I register the account?

Best regards,
Patrick

**Comment by gkralik** [comment]
Contact your SAP administrator for help on accessing the SAP support center‌.

**Comment by Bharath116** [comment]
> Contact your SAP administrator for help on accessing the SAP support center‌.

Cant we download package without   SAP administrator  help Sir

**Comment by gkralik** [comment]
No, you need a SAP account/license as far as I know.

**Comment by Bharath116** [comment]
Okay tq
