### ISSUE TITLE
How to set connection timeout

### ISSUE THREAD

**Issue by mdemori** [gkralik/php7-sapnwrfc#84]
Hello, 

currently the connection timeout seem set to around 60 seconds. I need to set te connection timeout to 10 or 20 seconds.. how can I set it? 

Thank you

**Comment by gkralik** [comment]
I am not aware of any setting in the SDK that affects the timeout.

**Comment by kj187** [comment]
Hey @mdemori 

the problem was a while ago, but have you found a solution to your problem in the meantime?

**Comment by fscholzspryker** [comment]
Hey, we are also very much interested in this functionality. Can we please reopen this issue @gkralik  ?

**Comment by gkralik** [comment]
As I already said, I am not aware of any setting in the SDK that affects connection timeout.
