### ISSUE TITLE
Failed test connection to SAP

### ISSUE THREAD

**Issue by ekobudis** [gkralik/php7-sapnwrfc#85]
Hello,

this is my first time use SAP connection, but i try to connect with parameter and failed to retrieved data from function module in sap. 

this test code :

```php
<?php
use SAPNWRFC\Connection as SapConnection;
use SAPNWRFC\Exception as SapException;

$config = [
    'ashost' => '192.168.122.113',
    'sysnr'  => '00',
    'client' => '100',
    'user'   => 'MM_RFX',
    'passwd' => '<redacted>',
    'trace'  => SapConnection::TRACE_LEVEL_OFF,
];

$options = [
    'use_function_desc_cache' => false,
];
    $c = new SapConnection($config,$options);

    $f = $c->getFunction('ZMMDI_WS_VEDNOR_LIST');
    $result = $f->invoke();
    var_dump($result);
```

thanks.

**Comment by gkralik** [comment]
Please don't post passwords. I edited you post.

What error do you get?

**Comment by ekobudis** [comment]
need configuration file sapnwrfc.ini

**Comment by gkralik** [comment]
A sapnwrfc.ini is not needed. What exactly does not work? Do you get an exception? If yes, provide the full error.

On 3 November 2019 14:33:07 CET, Shinobi Ta <notifications@github.com> wrote:
>need configuration file sapnwrfc.ini 
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/gkralik/php7-sapnwrfc/issues/85#issuecomment-549137027

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ekobudis** [comment]
the error from trace result is
NW RFC Library: SDK variant, Release 750 Patch Level 5, Compiled on Aug 20 2019 21:18:37
 CPIC library: 753.2019.02.22 version 3, NI library: 40, Kernel Release: 753 Patch Level 500
 Current working directory: /var/www/test, Program: php
 Hardware: AMD/Intel x86_64 with Linux x86_64, Operating_system: Linux 4.15.0-62-generic
 Hostname: ubuntu-1cpu-1gb-sg-sin1, IP address: 94.237.77.xxx, IPv6 address: fe80::543e:dfff:fe7a:76f4

2019-11-04 06:03:50.258514 [140331695545792] >> Error entry
        The UUID daemon (uuidd) is not active.
Please ask your system administrator to activate uuidd according to SAP note 1391070.

may be any something error from UUID?

**Comment by gkralik** [comment]
The UUID daemon is recommended, not mandatory.

Again, what is the exact error you are getting? If you cannot connect, there should be an exception. If the function call fails, there should be an exception. So wrap the code in a `try {} catch {}` and post the exception details. Otherwise no one will be able to help you.

**Comment by gkralik** [comment]
Please format your code properly. It helps with reading.

Again, there must be a proper error message. If you get a 502 Bad Gateway error look into your server logs. Also provide details on your environment (PHP version, SDK version). Did you follow the instruction at https://gkralik.github.io/php7-sapnwrfc/installation.html ?

Without a real error message I will not be able to provide help.

**Comment by ekobudis** [comment]
Thanks GKralik, after I'm check all parameter and any configuration this case is successful to test and done now.,
for information i use SAP NW RFC SDK 7.50 and PHP 7.2 & Laravel 5.7
