### ISSUE TITLE
errorInfo:DBSQL_STMNT_TOO_LARGE，Der Open SQL command is too big.

### ISSUE THREAD

**Issue by Wang-xiaozhang** [gkralik/php7-sapnwrfc#86]
大神,你好！一次查询大量的数据出现的错误:
errorInfo=['key'=>“DBSQL_STMNT_TOO_LARGE“，'message'=“Der Open SQL command is too big”],
请问这是SAPRFC的限制还是可以设置的？(英语不好，请见谅！)
--------------------------------------------------------------------
Hello,BIG God! An error occurred when querying a large number of data at one time:
errorInfo=['key'=>“DBSQL_STMNT_TOO_LARGE“，'message'=“Der Open SQL command is too big”],

Is this the limitation of saprfc or can it be set?

**Comment by gkralik** [comment]
This seems not to be related to the extension itself. Have a chat with your ABAP developer about that error.
