### ISSUE TITLE
some questions about sapnwrfc

### ISSUE THREAD

**Issue by patrickpdx** [gkralik/php7-sapnwrfc#87]
Hi there,

I have been tried using sapnwrfc, still not very clear. here are some questions:
I have tried to compile from scratch, have not made it work yet. my environment is windows platform (Apache 2.4.35, PHP 7.2.10), I saw there is some pre-built extensions for Windows (php_sapnwrfc-1.3.0-7.3.8-vc15-nts-x64.dll, php_sapnwrfc-1.3.0-7.3.8-vc15-nts-x86.dll, php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll, php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x86.dll).

1. Based on my environment, can I use these? 
2. if so, which one I can use? and how to config it, just copy this dll file to the PHP extension folder? any other files or setting I need?

Best regards,
Lin

**Comment by clcarver** [comment]
You need to have the SAP NW RFC library installed on the server (https://gkralik.github.io/php7-sapnwrfc/installation.html) and from SAP here (https://support.sap.com/en/product/connectors/nwrfcsdk.html). Then you can use one of the compiled PHP extensions and update your php.ini file to include it. Use it as detailed here https://gkralik.github.io/php7-sapnwrfc/usage.html

**Comment by patrickpdx** [comment]
Hi there,

Thanks for the information. sorry that I am kind new to this, not really sure I fully understand here.
I have our IT guy download the library for me and they extracted it for me, now i have two "nwrfcsdk_720" and "nwrfcsdk_750" (based on my environment, which one I should use?) , then what I need do next step? put this on my folder, then set PATH?

and sorry what does mean "and from SAP here...", is this place to get the files I mentioned above for "nwrfcsdk_720" and "nwrfcsdk_750"?

Please bare with me, really need your help to make it work.

Best regards,
Lin

**Comment by clcarver** [comment]
You can use whichever client version you want. There are some differences between the two so you should read up on which one would best suite your needs, but I am guessing either one would be fine. "and from SAP here" was just pointing to some documentation from SAP.

You should have a couple folders in your directory: bin, demo, doc, include, and lib. Set the lib folder in your PATH. That folder has the sapnwrfc.dll file. Enable the php extension in your php.ini, then in your php script new up your  SAPNWRFC\Connection and login. When you type php -m | grep "sap" in your cli you should see sapnwrfc. This is a good sign that the library was loaded correctly.

Are you getting any errors when you do this?

**Comment by patrickpdx** [comment]
Hi there,
Thanks for the information. but I am not able to make the sapnwrfc loaded.

This is what I did.
1. I rename the prebuilt file "php_sapnwrfc-1.3.0-7.3.8-vc15-nts-x86.dll" to "php_sapnwrfc.dll", then copy it to "php\ext" folder. then update the php.ini file to have the extension set.

2. copy the folde nwrfcsdk_720 to C driver, and rename it as "nwrfcsdk", then set PATH "C:\nwrfcsdk\lib",

3. restart the windows server and apache server.

after this, can see this extension loaded. anything I did wrong?

Regards,

**Comment by patrickpdx** [comment]
and I check the PHP log, here are the error:
[02-Jan-2020 21:53:03 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'sapnwrfc' (tried: c:/wamp/bin/php/php7.2.10/ext/sapnwrfc (The specified module could not be found.), c:/wamp/bin/php/php7.2.10/ext/php_sapnwrfc.dll (The specified module could not be found.)) in Unknown on line 0

**Comment by clcarver** [comment]
The error typically means it physically can't find the extension. I would try using a relative path vs the full path. Check your extension_dir var in your php.ini and play around a bit.

Second thing that jumps out is you are using php version 7.2.10 and the extension you are using is for php 7.3.8 (7.3.x) Not sure if that would cause some issues.

Lastly, the thing that bites me the most when setting things up is managing your extension architectures. I see you are using the x86 version, so make sure your php is also running x86 and not 64 bit. The error I typically see when that happens is php will say something along the lines of "Not a valid windows program" but you aren't getting that error.

Other than that, it looks like you have taken the right steps. Let me know how you make out. Good luck!

**Comment by gkralik** [comment]
Any updates?

**Comment by patrickpdx** [comment]
Hi clcaver/gkralik,

I still can't make it work. I have done the following things without luck:

1. using the relative path, system can't load sapnwrfc extension, and even can't load the other extensions either.

2. I have tried installing new version WAMSERVER 3.2.0 (Apache 2.2.8, PHP 7.3.12), doing all the stuff I mentioned previously, still not able to load the extension.

3. Also I tried installing SAP front GUI 7.40 on the server, no luck.

I am not sure what else I can do. kind frustrated here. my environment is WAMPSERVER, do you know any one ever tried the same thing successfully in this environment? I have successfully used the old version php_saprfc in the old version WAMPSERVER 2.0b (Apache 2.2.8, PHP 5.2.5) before.

Regards,
Patrick

**Comment by gkralik** [comment]
```
[02-Jan-2020 21:53:03 UTC] PHP Warning: PHP Startup: Unable to load dynamic library 'sapnwrfc' (tried: c:/wamp/bin/php/php7.2.10/ext/sapnwrfc (The specified module could not be found.), c:/wamp/bin/php/php7.2.10/ext/php_sapnwrfc.dll (The specified module could not be found.)) in Unknown on line 0
```

It looks like the extension cannot find the SAP NW RFC SDK libraries. Have you followed the [installation instructions](https://gkralik.github.io/php7-sapnwrfc/installation.html)?

**Comment by patrickpdx** [comment]
please see my very beginning post, I have asked our IT to downloaded and extracted "nwrfcsdk_720", I change the name to "nwrfcsdk", then put it under "C:\", set the PATH to point to "C:\nwrfcsdk\lib". The only thing I did not do is "Compiling the PHP extension". got the prebuilt extension mentioned above. then following the instruction "Enabling the extension".

anything missed?

Regards,

**Comment by gkralik** [comment]
Try to build the extension yourself. The pre-built DLLs are provided just for convenience and there might be problems if PHP versions, VC versions etc. don't match.

**Comment by sahuritesh** [comment]
Hi  gkralik sir,
I have compiled the sapnwrfc extension for windows IIS server and it was working fine earlier. all of a sudden the extension got disappeared from my installed extension of php. i can see the dll files and all the files are present but the extension is not loading and iam getting the below attached error. can you please let me know what exactly went wrong

The below is the response from the tests:
------------------------------------------------------------------------
![Uploading response.png…]()



TEST 84/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\086_can_call_invoke_without_parameters.phptSKIP Can call invoke() without parameters [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\086_can_call_invoke_without_parameters.phpt] reason: Missing configuration file sapnwrfc.config.inc
SKIP UTF-8 and UTF-16 strings are handled correctly. [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\087_can_handle_utf8_and_utf16_strings.phpt] reason: Missing configuration file sapnwrfc.config.inc
SKIP RemoteFunction::getName() returns the function's name. [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\088_function_has_accessor_for_name.phpt] reason: Missing configuration file sapnwrfc.config.inc
FAIL Returns string for RFC type BCD [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\089_returns_string_for_bcd.phpt]
TEST 88/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\090_throws_exception_if_not_given_int_for_iSKIP Throws TypeError if not given integer for RFC INT8 parameter. [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\090_throws_exception_if_not_given_int_for_int8 copy.phpt] reason: No suitable RFC to test.
TEST 89/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\cache\001_connection_constructor_accepts_opSKIP Connection constructor takes options hash as second parameter. [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\cache\001_connection_constructor_accepts_options_hash.phpt] reason: Missing configuration file sapnwrfc.config.inc
TEST 90/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\cache\002_function_can_be_invoked_after_cleSKIP An existing Function can be called after the cache was cleared. [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\cache\002_function_can_be_invoked_after_clearing_cache.phpt] reason: Missing configuration file sapnwrfc.config.inc
SKIP Clearing the function desc cache works. [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\cache\003_clear_function_desc_cache.phpt] reason: Missing configuration file sapnwrfc.config.inc
TEST 92/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\cache\004_lookup_function_with_cache_disablSKIP Looking up a function with disabled function desc cache works [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\cache\004_lookup_function_with_cache_disabled.phpt] reason: Missing configuration file sapnwrfc.config.inc
TEST 93/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\cache\005_clear_function_desc_cache_functioPASS clearFunctionDescCache function exists. [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\cache\005_clear_function_desc_cache_function_exists.phpt]
SKIP decfloat: returns string [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\decfloat\001_returns_string.phpt] reason: Missing configuration file sapnwrfc.config.inc
TEST 95/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\decfloat\002_accepts_string_int_double.phptSKIP decfloat: accepts string, int or double [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\decfloat\002_accepts_string_int_double.phpt] reason: Missing configuration file sapnwrfc.config.inc
TEST 96/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\function_description\001_method_exists.phptPASS RemoteFunction::getFunctionDescription() exists [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\function_description\001_method_exists.phpt]
TEST 97/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\function_description\002_returns_empty_arraSKIP RemoteFunction::getFunctionDescription() returns empty array for functions without parameters. [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\function_description\002_returns_empty_array_for_function_without_parameters.phpt] reason: Missing configuration file sapnwrfc.config.inc
TEST 98/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\function_description\003_returns_function_iSKIP RemoteFunction::getFunctionDescription() returns function interface as array. [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\function_description\003_returns_function_interface.phpt] reason: Missing configuration file sapnwrfc.config.inc
TEST 99/100 [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\function_description\004_complex_types_contSKIP RemoteFunction::getFunctionDescription() returns typedef for structures/tables. [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\function_description\004_complex_types_contain_typedef.phpt] reason: Missing configuration file sapnwrfc.config.inc
PASS Connection::getSSOTicket() exists [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\sso_ticket\001_method_exists.phpt]
=====================================================================
Number of tests :  100                25
Tests skipped   :   75 ( 75.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    1 (  1.0%) (  4.0%)
Tests passed    :   24 ( 24.0%) ( 96.0%)
---------------------------------------------------------------------
Time taken      :   26 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Returns string for RFC type BCD [C:\workspace\php\php-sdk\phpdev\vs16\x64\modules\sapnwrfc\tests\089_returns_string_for_bcd.phpt]
=====================================================================
NMAKE : fatal error U1077: 'C:\workspace\php\php-sdk\phpdev\vs16\x64\php-8.1.23-src\x64\Release\php.exe' : return code '0x1'
Stop.

C:\workspace\php\php-sdk\phpdev\vs16\x64\php-8.1.23-src

**Comment by sahuritesh** [comment]
The version which iam using is PHP 8.1.23, windows NT IIS Server

![image](https://github.com/gkralik/php7-sapnwrfc/assets/35589805/9749e454-7378-4210-ac96-719dc0963abe)
