### ISSUE TITLE
undefined function

### ISSUE THREAD

**Issue by beneluxs** [gkralik/php7-sapnwrfc#88]
Hello,

As per your documentation when I calling \SAPNWRFC\clearFunctionDescCache('ZHR_PHP_PAYSY');
it's throwing an exception undefined function clearFunctionDescCache()

in my php file I just put \SAPNWRFC\clearFunctionDescCache('ZHR_PHP_PAYSY'); line nothing else 

ZHR_PHP_PAYSY is my function module name this function module was change few days ago and one parameter has been added.

please help

**Comment by gkralik** [comment]
Which version of the extension are you using? The function ` \SAPNWRFC\clearFunctionDescCache($fn)` has only been added in version 1.3.0 (see [Changelog](https://github.com/gkralik/php7-sapnwrfc/blob/master/CHANGELOG.md#130---2019-02-23))

**Comment by beneluxs** [comment]
Thank You
