### ISSUE TITLE
extension won't load

### ISSUE THREAD

**Issue by shokarta** [gkralik/php7-sapnwrfc#89]
Hello,

as far I am aware, I have tried everything.
Win10 64x
PHP Version 7.3.4
Architecture x64
Thread Safety enabled
(copied from phpinfo();)

php.ini:
extension=php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll
file is saved as "php/ext/php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll"
 - both is ctrl+c so here is no typo...

when run php-cgi.exe i have this error:
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll' (tried: \xampp\php\ext\php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll (Uveden´┐Ż modul nebyl nalezen.), \xampp\php\ext\php_php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll.dll (Uveden´┐Ż modul nebyl nalezen.)) in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library 'php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll' (tried: \xampp\php\ext\php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll (Uveden´┐Ż modul nebyl nalezen.), \xampp\php\ext\php_php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll.dll (Uveden´┐Ż modul nebyl nalezen.)) in <b>Unknown</b> on line <b>0</b><br />

However the file IS THERE!

error.log confirms that with no futher info:
PHP Warning:  PHP Startup: Unable to load dynamic library 'php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll' (tried: \\xampp\\php\\ext\\php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll (Uveden\xef\xbf\xbd modul nebyl nalezen.), \\xampp\\php\\ext\\php_php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64.dll.dll (Uveden\xef\xbf\xbd modul nebyl nalezen.)) in Unknown on line 0

it is not shown in phpinfo() not even on php -m, there its not loaded.

I have tried the x86 version, and php-cgi.exe gave me error that this is win32 version, so it at least recognized the file.

File was downloaded as precompiled from you website

Now im lost, what else to check, how to proceed to debug :(

**Comment by shokarta** [comment]
EDIT, tried to remove .dll from php.ini:
extension=php_sapnwrfc-1.3.0-7.3.8-vc15-ts-x64
 - i have noticed that in php.ini for some extensions i use .dll and for some not, but all others work fine

There was no result change whatsoever

PS: I cant modify initial post, but basicaly my language says "Uvedeny modul nebyl nalezen" => "The specified module could not be found"

also, php.ini:
extension_dir = "\xampp\php\ext"
 - so its also fine

**Comment by gkralik** [comment]
Have you checked file permissions?

**Comment by shokarta** [comment]
Yes, same as any other dll in the ext directory

**Comment by gkralik** [comment]
Any updates?

**Comment by shokarta** [comment]
Unfortunatelly not at all, Im stuck at the same place where I was… I have tried all precompiled versions, several php versions, but no luck…
Can you recommend some recent EXACT XAMPP version where you made this work?

**Comment by gkralik** [comment]
Have you tried to compile the extension yourself? The precompiled DLLs are provided for convenience only and there is no guarantee they will work on all machines.

**Comment by shokarta** [comment]
Issue fixed, I redownloaded the SAP SDK from support SAP page and now it works.
All filenames was corrected, but in one file i noticed different filesize, so I believe it was corrupted.
However, would be good feature if you can make some startup warning, that your lib will not work because it can not reach/open the sap SDK files.. so it can at least point people where the problem is.
Thank you :)
