### ISSUE TITLE
Improve Windows build documentation

### ISSUE THREAD

**Issue by gkralik** [gkralik/php7-sapnwrfc#90]
Update the Windows build instructions to use PHP's new Windows SDK .

**Comment by avadaneidanut** [comment]
@gkralik I can help with this, I’ll make a pull request on the docs. Should I make the instructions for the latest versions of php? 7.2 and greater?

**Comment by gkralik** [comment]
Yes, 7.2 and up would be best. I tried it last week using the new SDK and it seems much easier to build now. If you can help, that would be much appreciated.

**Comment by gkralik** [comment]
I've added support for specifiying a path to the NW RFC SDK using `--with-sapnwrfc=PATH` in 47a31e29626828f8f9ad76f253ff3521952895c7. This should help keeping the PHP build directory clean (no need to copy the SDK files into the PHP source tree).

**Comment by avadaneidanut** [comment]
@gkralik Should I make the instructions for the master branch?

**Comment by gkralik** [comment]
Yes.

**Comment by szabizs** [comment]
This should solve my 7.4.2 build issue also?

**Comment by avadaneidanut** [comment]
@gkralik I'll wait for the 2.0.0 release before doing this.
