### ISSUE TITLE
Not valid Win32 application

### ISSUE THREAD

**Issue by vilda72** [gkralik/php7-sapnwrfc#92]
Hi guys, 
I have issue with installing your php7-sapnwrfc. Here is my environment:

Windows Server 2012 Standard, 64b
PHP 7.4.3 x64
php -v
PHP 7.4.3 (cli) (built: Feb 18 2020 17:29:46) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

I have downloaded release php_sapnwrfc-1.3.0-7.4.3-vc15-ts-x64.dll from https://github.com/gkralik/php7-sapnwrfc/releases, rename it as php_sapnwrfc.dll and add to php.ini. Sapnwrfc is not loaded well in php -m, I got warning:

Warning: PHP Startup: Unable to load dynamic library 'php_sapnwrfc.dll' (tried:
C:\PHP7.4TS\ext\php_sapnwrfc.dll (%1 is not a valid Win32 application.)

I have SAP Gui 7.40. C:\nwrfcsdk\lib\ is added to PATH and there is sapnwrfc.dll.

I have found thread https://github.com/gkralik/php7-sapnwrfc/issues/37 where is the same issue. I tried to copy other sapnwrfc.dll version from SAP GUI 750 or 760 but error is still there. I also tried 32 or 64 bit version of sapnwrfc.dll

Interesting is that on my local PC works everything fine with the same versions (only Windows is 10 64b).

Do you have any idea what can I do with this?
Thanks,
vilda

**Comment by gkralik** [comment]
Try to compile the extension from source.
