### ISSUE TITLE
Connection options

### ISSUE THREAD

**Issue by MarcioRM78** [gkralik/php7-sapnwrfc#93]
Hi!

Can I use any of the options below in php7-sapnwrfc connection to SAP?

  -h <ashost>          SAP application server to connect to this needs to include the SAP router string if applicable
  -s <sysnr>           system number of the target SAP system
  -u <user>            user
  -p <passwd>          password
  -c <client>          client
  -l <language>        logon language
  -D <destination>     destination defined in RFC config file sapnwrfc.ini
  -F <function>        function module to be called, only EDI_DATA_INCOMING or EDI_STATUS_INCOMING is supported
  -E PATHNAME=<path>   path, including file name, to EDI data file or status file, with maximum length of 100 charachters
  -E PORT=<port name>  port name of the ALE/EDI interface with maximum length of 10 charachters
  -t                   enable RFC trace
  -help  or -?         display this help page
  -v                   display the version of the NWRFC library and the version of the compiler used by SAP to build this program
  -i                   connect to the target system and display the system info

In fact I need to specify the parameter language, if possible.

Thanks in advance for your attention

**Comment by gkralik** [comment]
See [Connecting to a SAP system](https://gkralik.github.io/php7-sapnwrfc/usage.html#connecting-to-a-sap-system) for options you can use.
