### ISSUE TITLE
SAPRFC legacy code migration

### ISSUE THREAD

**Issue by ladenise** [gkralik/php7-sapnwrfc#94]
Hello,

First of all, thanks for the contribution.
I'm trying to migrate a legacy app using your lib.

I have a problem calling a function (FUNCTION_NAME in example below) where I need to append a value (123 in the example below) at the end of an internal table (TABLE1 in the example below) as a way to filter the results.
I tried invoking the function as below:

```
$function = $connection->getFunction('FUNCTION_NAME');

$returnValue = $function->invoke([
	'PARAMETER1' => 'PARAMETER1_VALUE',
	'TABLE1' => ['TABLE1_FIELD' => '123'],
]);

```
But I get the following message:
`Failed to set TABLE row, expected array for parameter TABLE1
`

Could you please help me find out the solution?
Thanks in advance.

**Comment by ladenise** [comment]
Just adding a little detail.
In the legacy app, the PARAMETER1 was set with a saprfc_import function.
While the TABLE1 was set with a saprfc_table_append function.

**Comment by gkralik** [comment]
The error `Failed to set TABLE row, expected array for parameter TABLE1 ` is caused by wrong parameter format in the `ìnvoke()` call.

Table parameters expect arrays of arrays, so something like this should work:
```php
$function = $connection->getFunction('FUNCTION_NAME');

$returnValue = $function->invoke([
	'PARAMETER1' => 'PARAMETER1_VALUE',
	'TABLE1' => [
            ['TABLE1_FIELD' => '123'],
        ],
]);
```

**Comment by ladenise** [comment]
It works perfectly. Thank you.
