### ISSUE TITLE
Point _zend_hash_index_update@@24 could not be located

### ISSUE THREAD

**Issue by fikusir** [gkralik/php7-sapnwrfc#98]
Hi guys,

Have this issue comming from apache: The procedure entry point _zend_hash_index_update@@24 could not be located in the dynamic link library

Running on Win10 64bit with Xampp 3.2.4 installed. Php version is 7.2.27 64bit.

I installed downloaded SAP NW RFC SDK 7.50 and exported bz 7zip co C:. Added the path to this directory in Enviroment. When I rename C:\nwrfcsdk to something else then the error is gone, so think here I am fine.

Added php_sapnwrfc-1.3.0-7.4.3-vc15-ts-x64.dll into php/ext/ as php_sapnwrfc.dll.

Any help appriciated, thanks!

**Comment by gkralik** [comment]
You said you are using PHP 7.2.27, but you have the extension DLL for PHP 7.4.3. That probably won't work.
