### ISSUE TITLE
Datatype RFCTYPE_DECF34

### ISSUE THREAD

**Issue by andipohl** [gkralik/php7-sapnwrfc#99]
We want to call a function that returns a table. In this table, a field has the data type **RFCTYPE_DECF34**.
The call fails with the error message:

`Unknown type for parameter KAQTY.`

It comes from rfc_parameters.c:rfc_get_field_value.

Is it possible to implement support for this data type?

**Comment by gkralik** [comment]
I will have a look at this.

**Comment by gkralik** [comment]
Support for `DECFLOAT16` and `DECFLOAT34` is now in `master`.

Both types are mapped to PHP strings to prevent rounding errors.

**Comment by andipohl** [comment]
Great! I have tested it under Linux. 

It's working as expected.
